<div class="panel panel-default">
	<div class="panel-body">
		<h1 style="text-align:center">Accepted papers</h1>
		<!--h2>Committees</h2-->

		<h1>CMSB 2016 Accepted Papers</h1>
<!-- <style>.accepted {clear:right;margin-bottom:20pt;padding:3pt}</style>
<style>.abstract {border-left: solid black 1px;border-right: solid black 1px;border-top: solid black 1px;padding:3pt}</style>
<style>.paper {border-left: solid black 1px;border-right: solid black 1px;border-top: solid black 1px;padding:2pt}</style>
<style>.abstract:last-child {border-bottom: solid black 1px;padding:3pt}</style>
<style>.paper:last-child {border-bottom: solid black 1px;padding:2pt}</style> -->
<ul class="list-group">

	<h3>Tool papers</h3>
	<li class="list-group-item">
		<span class="authors"><a href="https://sites.google.com/site/alexfvillaverde/">Alejandro F. Villaverde</a>, Kolja Becker and <a href="http://gingproc.iim.csic.es/~julio/">Julio R. Banga</a>.</span>
		<span class="title">PREMER: parallel reverse engineering of biological networks with information theory</span>
	</li>
	<ul class="list-group">
	<li class="list-group-item">
		<span class="authors">Matej Troják, David Šafránek, Jakub Hrabec, Jakub Šalagovič, Františka Romanovská and Jan Červený.</span>
		<span class="title">E-cyanobacterium.org: A Web-based Platform for Systems Biology of Cyanobacteria</span>
	</li>
	<li class="list-group-item">
		<span class="authors"><a href="http://wwwen.uni.lu/recherche/fstc/computer_science_and_communications_research_unit/members/andrzej_mizera">Andrzej Mizera</a>, <a href="http://satoss.uni.lu/jun">Jun Pang</a> and Qixia Yuan.</span>
		<span class="title">ASSA-PBN 2.0: A Software Tool for Probabilistic Boolean Networks</span>
	</li>
</ul>

<h3>Regular papers</h3>
	<li class="list-group-item">
		<span class="authors">Qinsi Wang, Natasa Miskov-Zivanov, Bing Liu, James Faeder, Michael Lotze and Edmund Clarke.</span>
		<span class="title">Formal Modeling and Analysis of Pancreatic Cancer Microenvironment</span>
	</li>
	<li class="list-group-item">
		<span class="authors">Chieh Lo and Radu Marculescu.</span>
		<span class="title">Autonomous and Adaptive Control of Populations of Bacteria through Environment Regulation</span>
	</li>
	<li class="list-group-item">
		<span class="authors">Jasha Sommer-Simpson, John Reinitz, Leonid Fridlyand, Louis Philipson and Ovidiu Radulescu.</span>
		<span class="title">Hybrid reductions of computational models of voltage-gated ion channels coupled to cellular biochemistry</span>
	</li>
	<li class="list-group-item">
		<span class="authors">Michael Backenköhler, <a href="http://bortolussi.dmg.units.it">Luca Bortolussi</a> and <a href="http://mosi.cs.uni-saarland.de">Verena Wolf</a>.</span>
		<span class="title">Generalized Method of Moments for Stochastic Reaction Networks in Equilibrium</span>
	</li>
	<li class="list-group-item">
		<span class="authors"><a href="http://wwwen.uni.lu/recherche/fstc/computer_science_and_communications_research_unit/members/andrzej_mizera">Andrzej Mizera</a>, <a href="http://satoss.uni.lu/jun">Jun Pang</a> and Qixia Yuan.</span>
		<span class="title">Fast Simulation of Probabilistic Boolean Networks</span>
	</li>
	<li class="list-group-item">
		<span class="authors"><a href="http://loicpauleve.name">Loïc Paulevé</a>. </span>
		<span class="title">Goal-Oriented Reduction of Automata Networks</span>
	</li>
	<li class="list-group-item">
		<span class="authors">Carolin Loos, Anna Fiedler and Jan Hasenauer.</span>
		<span class="title">Parameter estimation for reaction rate equation constrained mixture models</span>
	</li>
	<li class="list-group-item">
		<span class="authors">Martin Demko, Nikola Benes, Lubos Brim, Samuel Pastva and David Šafránek.</span>
		<span class="title">High-Performance Symbolic Parameter Synthesis of Biological Models: A Case Study</span>
	</li>
	<li class="list-group-item">
		<span class="authors"><a href="http://www.di.ens.fr/~feret">Jerome Feret</a> and <a href="http://www.di.ens.fr/~quyen/">Quyen Kim Ly</a>.</span>
		<span class="title">Local traces: an over-approximation of the behaviour of the proteins in rule-based models</span>
	</li>
	<li class="list-group-item">
		<span class="authors">Chunyan Mu, Peter Dittrich, <a href="http://www.cs.bham.ac.uk/~parkerdx/">David Parker</a> and Jonathan E. Rowe.</span>
		<span class="title">Formal Quantitative Analysis of Reaction Networks Using Chemical Organisation Theory</span>
	</li>
	<li class="list-group-item">
		<span class="authors">Elisa Tonello, <a href="http://www.cristal.univ-lille.fr/~madelain/">Guillaume Madelaine</a>, Etienne Farcot, <a href="http://www.cristal.univ-lille.fr/~lhoussai/">Cedric Lhoussaine</a> and <a href="http://researchers.lille.inria.fr/~niehren">Joachim Niehren</a>.</span>
		<span class="title">Normalizing Chemical Reaction Networks by Confluent Structural Simplification</span>
	</li>
	<li class="list-group-item">
		<span class="authors"><a href="http://www3.cs.stonybrook.edu/~mdaislam">Md. Ariful Islam</a>, Greg Byrne, <a href="http://www.cs.cmu.edu/~soonhok">Soonho Kong</a>, <a href="http://www.cs.cmu.edu/~emc">Edmund Clarke</a>, <a href="https://www.cs.umd.edu/~rance">Rance Cleaveland</a>, <a href="https://ti.tuwien.ac.at/cps/people/grosu">Radu Grosu</a> and <a href="http://www3.cs.stonybrook.edu/~sas/">Scott Smolka</a>.</span>
		<span class="title">Bifurcation Analysis of Cardiac Alternans using  δ-Decidability</span>
	</li>
	<li class="list-group-item">
		<span class="authors"><a href="http://lifeware.inria.fr/~fages">François Fages</a>, Thierry Martinez, David Rosenblueth and <a href="http://lifeware.inria.fr/~soliman/">Sylvain Soliman</a>.</span>
		<span class="title">Influence Systems vs Reaction Systems</span>
	</li>
	<li class="list-group-item">
		<span class="authors">Luca Laurenti, <a href="http://LucaCardelli.name/">Luca Cardelli</a> and <a href="http://www.cs.ox.ac.uk/people/marta.kwiatkowska/">Marta Kwiatkowska</a>.</span>
		<span class="title">A Stochastic Hybrid Approximation for Chemical Kinetics Based on the Linear Noise Approximation</span>
	</li>
	<li class="list-group-item">
		<span class="authors"><a href="http://www.irccyn.ec-nantes.fr/~benabdal/">Emna Ben Abdallah</a>, <a href="http://tony.research.free.fr/">Tony Ribeiro</a>, <a href="http://www.irccyn.ec-nantes.fr/~magnin/">Morgan Magnin</a>, <a href="http://www.irccyn.ec-nantes.fr/~roux/">Olivier Roux</a> and <a href="http://research.nii.ac.jp/~inoue">Katsumi Inoue</a>.</span>
		<span class="title">Inference of delayed biological regulatory networks from time series data</span>
	</li>
	<li class="list-group-item">
		<span class="authors"><a href="https://sites.google.com/site/giuliocaravagna/">Giulio Caravagna</a>, <a href="http://bortolussi.dmg.units.it">Luca Bortolussi</a> and Guido Sanguinetti.</span>
		<span class="title">Matching models across abstraction levels with Gaussian Processes</span>
	</li>
	<li class="list-group-item">
		<span class="authors"><a href="http://combio.abo.fi/~eczeizle/">Eugen Czeizler</a>, Cristian Gratie, Krishna Kanhaiya and <a href="http://www.users.abo.fi/ipetre">Ion Petre</a>.</span>
		<span class="title">Target Controllability of Linear Networks</span>
	</li>
</ul>
</div>
</div>


