<div class="panel panel-default">
	<div class="panel-body">
		<h1 style="text-align:center">Accepted papers</h1>
		<!--h2>Committees</h2-->

<!-- <style>.accepted {clear:right;margin-bottom:20pt;padding:3pt}</style>
<style>.abstract {border-left: solid black 1px;border-right: solid black 1px;border-top: solid black 1px;padding:3pt}</style>
<style>.paper {border-left: solid black 1px;border-right: solid black 1px;border-top: solid black 1px;padding:2pt}</style>
<style>.abstract:last-child {border-bottom: solid black 1px;padding:3pt}</style>
<style>.paper:last-child {border-bottom: solid black 1px;padding:2pt}</style> -->

<h3>Tool papers</h3>
<ul class="list-group">

	<li class="list-group-item">
		<span class="authors"><a href="https://sites.google.com/site/alexfvillaverde/">Alejandro F. Villaverde</a>, Kolja Becker and <a href="http://gingproc.iim.csic.es/~julio/">Julio R. Banga</a>.</span>
		<span class="papertitle" data-toggle="collapse" data-target="#98590311">PREMER: parallel reverse engineering of biological networks with information theory</span>
		<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590311"/>
	</li>
	<li class="list-group-item">
		<span class="authors">Matej Troják, David Šafránek, Jakub Hrabec, Jakub Šalagovič, Františka Romanovská and Jan Červený.</span>
		<span class="papertitle" data-toggle="collapse" data-target="#98590305">E-cyanobacterium.org: A Web-based Platform for Systems Biology of Cyanobacteria</span>
		<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590305"/>
	</li>
	<li class="list-group-item">
		<span class="authors"><a href="http://wwwen.uni.lu/recherche/fstc/computer_science_and_communications_research_unit/members/andrzej_mizera">Andrzej Mizera</a>, <a href="http://satoss.uni.lu/jun">Jun Pang</a> and Qixia Yuan.</span>
		<span class="papertitle" data-toggle="collapse" data-target="#98590298">ASSA-PBN 2.0: A Software Tool for Probabilistic Boolean Networks</span>
		<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590298"/>
	</li>
</ul>

<h3>Regular papers</h3>
<ul class="list-group">
	<li class="list-group-item">
		<span class="authors">Qinsi Wang, Natasa Miskov-Zivanov, Bing Liu, James Faeder, Michael Lotze and Edmund Clarke.</span>
		<span class="papertitle" data-toggle="collapse" data-target="#98590281">Formal Modeling and Analysis of Pancreatic Cancer Microenvironment</span>
		<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590281"/>
	</li>
	<li class="list-group-item">
		<span class="authors">Chieh Lo and Radu Marculescu.</span>
		<span class="papertitle" data-toggle="collapse" data-target="#98590163">Autonomous and Adaptive Control of Populations of Bacteria through Environment Regulation</span>
		<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590163"/>
	</li>
	<li class="list-group-item">
		<span class="authors">Jasha Sommer-Simpson, John Reinitz, Leonid Fridlyand, Louis Philipson and Ovidiu Radulescu.</span>
		<span class="papertitle" data-toggle="collapse" data-target="#98590266">Hybrid reductions of computational models of voltage-gated ion channels coupled to cellular biochemistry</span>
		<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590266"/>
	</li>
	<li class="list-group-item">
		<span class="authors">Michael Backenköhler, <a href="http://bortolussi.dmg.units.it">Luca Bortolussi</a> and <a href="http://mosi.cs.uni-saarland.de">Verena Wolf</a>.</span>
		<span class="papertitle" data-toggle="collapse" data-target="#98590013">Generalized Method of Moments for Stochastic Reaction Networks in Equilibrium</span>
		<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590013"/>
	</li>
	<li class="list-group-item">
		<span class="authors"><a href="http://wwwen.uni.lu/recherche/fstc/computer_science_and_communications_research_unit/members/andrzej_mizera">Andrzej Mizera</a>, <a href="http://satoss.uni.lu/jun">Jun Pang</a> and Qixia Yuan.</span>
		<span class="papertitle" data-toggle="collapse" data-target="#98590210">Fast Simulation of Probabilistic Boolean Networks</span>
		<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590210"/>
	</li>
	<li class="list-group-item">
		<span class="authors"><a href="http://loicpauleve.name">Loïc Paulevé</a>. </span>
		<span class="papertitle" data-toggle="collapse" data-target="#98590246">Goal-Oriented Reduction of Automata Networks</span>
		<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590246"/>
	</li>
	<li class="list-group-item">
		<span class="authors">Carolin Loos, Anna Fiedler and Jan Hasenauer.</span>
		<span class="papertitle" data-toggle="collapse" data-target="#98590180">Parameter estimation for reaction rate equation constrained mixture models</span>
		<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590180"/>
	</li>
	<li class="list-group-item">
		<span class="authors">Martin Demko, Nikola Benes, Lubos Brim, Samuel Pastva and David Šafránek.</span>
		<span class="papertitle" data-toggle="collapse" data-target="#98590080">High-Performance Symbolic Parameter Synthesis of Biological Models: A Case Study</span>
		<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590080"/>
	</li>
	<li class="list-group-item">
		<span class="authors"><a href="http://www.di.ens.fr/~feret">Jerome Feret</a> and <a href="http://www.di.ens.fr/~quyen/">Quyen Kim Ly</a>.</span>
		<span class="papertitle" data-toggle="collapse" data-target="#98590113">Local traces: an over-approximation of the behaviour of the proteins in rule-based models</span>
		<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590113"/>
	</li>
	<li class="list-group-item">
		<span class="authors">Chunyan Mu, Peter Dittrich, <a href="http://www.cs.bham.ac.uk/~parkerdx/">David Parker</a> and Jonathan E. Rowe.</span>
		<span class="papertitle" data-toggle="collapse" data-target="#98590226">Formal Quantitative Analysis of Reaction Networks Using Chemical Organisation Theory</span>
		<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590226"/>
	</li>
	<li class="list-group-item">
		<span class="authors">Elisa Tonello, <a href="http://www.cristal.univ-lille.fr/~madelain/">Guillaume Madelaine</a>, Etienne Farcot, <a href="http://www.cristal.univ-lille.fr/~lhoussai/">Cedric Lhoussaine</a> and <a href="http://researchers.lille.inria.fr/~niehren">Joachim Niehren</a>.</span>
		<span class="papertitle" data-toggle="collapse" data-target="#98590195">Normalizing Chemical Reaction Networks by Confluent Structural Simplification</span>
		<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590195"/>
	</li>
	<li class="list-group-item">
		<span class="authors"><a href="http://www3.cs.stonybrook.edu/~mdaislam">Md. Ariful Islam</a>, Greg Byrne, <a href="http://www.cs.cmu.edu/~soonhok">Soonho Kong</a>, <a href="http://www.cs.cmu.edu/~emc">Edmund Clarke</a>, <a href="https://www.cs.umd.edu/~rance">Rance Cleaveland</a>, <a href="https://ti.tuwien.ac.at/cps/people/grosu">Radu Grosu</a> and <a href="http://www3.cs.stonybrook.edu/~sas/">Scott Smolka</a>.</span>
		<span class="papertitle" data-toggle="collapse" data-target="#98590128">Bifurcation Analysis of Cardiac Alternans using  δ-Decidability</span>
		<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590128"/>
	</li>
	<li class="list-group-item">
		<span class="authors"><a href="http://lifeware.inria.fr/~fages">François Fages</a>, Thierry Martinez, David Rosenblueth and <a href="http://lifeware.inria.fr/~soliman/">Sylvain Soliman</a>.</span>
		<span class="papertitle" data-toggle="collapse" data-target="#98590095">Influence Systems vs Reaction Systems</span>
		<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590095"/>
	</li>
	<li class="list-group-item">
		<span class="authors">Luca Laurenti, <a href="http://LucaCardelli.name/">Luca Cardelli</a> and <a href="http://www.cs.ox.ac.uk/people/marta.kwiatkowska/">Marta Kwiatkowska</a>.</span>
		<span class="papertitle" data-toggle="collapse" data-target="#98590143">A Stochastic Hybrid Approximation for Chemical Kinetics Based on the Linear Noise Approximation</span>
		<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590143"/>
	</li>
	<li class="list-group-item">
		<span class="authors"><a href="http://www.irccyn.ec-nantes.fr/~benabdal/">Emna Ben Abdallah</a>, <a href="http://tony.research.free.fr/">Tony Ribeiro</a>, <a href="http://www.irccyn.ec-nantes.fr/~magnin/">Morgan Magnin</a>, <a href="http://www.irccyn.ec-nantes.fr/~roux/">Olivier Roux</a> and <a href="http://research.nii.ac.jp/~inoue">Katsumi Inoue</a>.</span>
		<span class="papertitle" data-toggle="collapse" data-target="#98590028">Inference of delayed biological regulatory networks from time series data</span>
		<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590028"/>
	</li>
	<li class="list-group-item">
		<span class="authors"><a href="https://sites.google.com/site/giuliocaravagna/">Giulio Caravagna</a>, <a href="http://bortolussi.dmg.units.it">Luca Bortolussi</a> and Guido Sanguinetti.</span>
		<span class="papertitle" data-toggle="collapse" data-target="#98590048">Matching models across abstraction levels with Gaussian Processes</span>
		<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590048"/>
	</li>
	<li class="list-group-item">
		<span class="authors"><a href="http://combio.abo.fi/~eczeizle/">Eugen Czeizler</a>, Cristian Gratie, Krishna Kanhaiya and <a href="http://www.users.abo.fi/ipetre">Ion Petre</a>.</span>
		<span class="papertitle" data-toggle="collapse" data-target="#98590065">Target Controllability of Linear Networks</span>
		<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590065"/>
	</li>
</ul>

<br>
<h1 style="text-align:center">Accepted posters</h1>

<ul class="list-group">

	<li class="list-group-item">
		<span class="authors">Priya Anand, Monika Borkowska-Panek, Karin Fink and <a href="http://www.int.kit.edu/wenzel.php">Wolfgang Wenzel</a>.</span>
		<span class="papertitle" data-toggle="collapse" data-target="#98590318">Modelling Peptide Adsorption on Inorganic Surfaces</span>
		<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590318"/>
	</li>

	<li class="list-group-item">
		<span class="authors"><a href="http://loicpauleve.name">Loïc Paulevé</a>.</span>
		<span class="papertitle" data-toggle="collapse" data-target="#98590326">Pint, a static analyzer for dynamics of Automata Networks</span>
		<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590326"/>
	</li>

	<li class="list-group-item">
		<span class="authors">Nadia S. M. Goncalves, Samuel M. D. Oliveira, Jose M. Fonseca and Andre S. Ribeiro.</span>
		<span class="papertitle" data-toggle="collapse" data-target="#98590321">Temperature Dependence of Leakiness of Transcription Repression Mechanisms of Escherichia coli</span>
		<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590321"/>
	</li>

	<li class="list-group-item">
		<span class="authors"><a href="http://wwwen.uni.lu/recherche/fstc/computer_science_and_communications_research_unit/members/andrzej_mizera">Andrzej Mizera</a>, <a href="http://satoss.uni.lu/jun">Jun Pang</a> and Qixia Yuan.</span>
		<span class="papertitle" data-toggle="collapse" data-target="#98590323">GPU-accelerated Steady-State Analysis of Probabilistic Boolean Networks</span>
		<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590323"/>
	</li>
	<li class="list-group-item">
		<span class="authors"><a href="http://www.mrc-hnr.cam.ac.uk/people/james-smith/">James Smith</a>, Kai Loell and Albert Koulman.</span>
		<span class="papertitle" data-toggle="collapse" data-target="#98590333">Revealing biomarker mixtures in lipid pools from large-scale lipidomics</span>
		<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590333"/>
	</li>
	<li class="list-group-item">
		<span class="authors"><a href="http://www.mrc-hnr.cam.ac.uk/people/james-smith/">James Smith</a> and Ahmed Ibrahim.</span>
		<span class="papertitle" data-toggle="collapse" data-target="#98590332">Game theoretic consideration of transgenic bacteria in the human gut microbiota converting omega-6 to omega-3 fats</span>
		<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590332"/>
	</li>

	<li class="list-group-item">
		<span class="authors">Benjamin Hall, <a href="http://www.cs.le.ac.uk/people/npiterman">Nir Piterman</a> and <a href="http://research.microsoft.com/~jfisher/">Jasmin Fisher</a>.</span>
		<span class="papertitle" data-toggle="collapse" data-target="#98590328">Linear Temporal Logic for Biologists in BMA</span>
		<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590328"/>
	</li>
	<li class="list-group-item">
		<span class="authors">Mariana Esther Sanchez, Elena Alvarez-Buylla and Marcia Hiriart.</span>
		<span class="papertitle" data-toggle="collapse" data-target="#sanchez_et_al">The CD4+ T cell regulatory network mediates inflammatory responses during acute hyperinsulinemia</span>
		<p class="collapse just list-group-item-text" style="font-size: 90%" id="sanchez_et_al"/>
	</li>

	<li class="list-group-item">
		<span class="authors">David Shorthouse, Angela Riedel, Jacqueline Shields and Benjamin Hall.</span>
		<span class="papertitle" data-toggle="collapse" data-target="#98590330">Deregulation of Osmotic Regulation Machinery Explains and Predicts Cellular Transformation in Cancer and Disease</span>
		<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590330"/>
	</li>
</ul>


</div>
</div>


