<div class="panel panel-default">
	<div class="panel-body">
		<h1 style="text-align:center">Call for Papers</h1>
		<h2>Topics</h2>
		<p>CMSB 2016 solicits original research articles on the analysis of biological systems, networks, data, and corresponding application domains. The conference brings together computer scientists, biologists, mathematicians, engineers, and physicists interested in a system-level understanding of biological processes.</p>
		<p>Topics of interest include, but are not limited to:</p>
		<ul>
			<li>formalisms for modelling biological processes</li>
			<li>models and their biological applications</li>
			<li>frameworks for model verification, validation, analysis and simulation of biological systems</li>
			<li>high-performance Computational Systems Biology and parallel implementations</li>
			<li>model inference from experimental data</li>
			<li>model integration from biological databases</li>
			<li>multi-scale modelling and analysis methods</li>
			<li>methods for synthetic biology and biomolecular computing</li>
		</ul>
		<p>Papers should be submitted to one of the following categories:</p>
		<ul>
<!--li>Theory</li>
<li>High performance methods</li>
<li>Tools</li>
<li>Case studies (applications of systems biology methods to real cases or new open questions in biology that require a systems biology approach)</li-->
	<li>Regular papers</li>
	<li>Tool papers</li>
</ul>

<!--p><a href="https://easychair.org/conferences/?conf=cmsb2016">Click here to submit to easychair.</a></p-->
<p><a class="btn btn-warning">Submissions are now closed</a></p>

<h2>Proceedings</h2>
<p>Proceedings of CMSB 2016 will be published as a volume in <strong>Springer's Lecture Notes in Computer Science / Lecture Notes in Bioinformatics series (LNCS/LNBI).</strong></p>
<p>After the conference, a selection of papers will be invited to be 
	extended and submitted to a special issue of the journal <a href="https://www.computer.org/web/tcbb/about-tcbb">IEEE/ACM 
	Transactions on Computational Biology and Bioinformatics</a>.</p>

	<h2>Format for regular papers</h2>
	Regular papers should describe original work that has not been previously published and is not under review for publication elsewhere. Papers must be written in English and must conform the LNCS style (instructions for authors with LaTeX and Word styles can be found <a href="http://www.springer.com/computer/lncs?SGWID=0-164-6-793341-0">here</a>). They have to be submitted electronically as PDF files via EasyChair. <strong>The limit for submissions is 15 pages</strong>, including references. Appendices will not be counted in the page limit.

	<h2>Format and guidelines for tool papers</h2>
	Tool papers should present new tools, new tool components or novel
	extensions to existing tools supporting the modelling and analysis of biological systems. Each
	submission should be original and not published previously in a tool
	paper form.

	Papers must be written in English and must conform the LNCS style (instructions for authors with LaTeX and Word styles can be found <a href="http://www.springer.com/computer/lncs?SGWID=0-164-6-793341-0">here</a>). They have to be submitted electronically as PDF files via EasyChair. <strong>The limit for submissions is 6 pages</strong>. Appendices will not be counted in the page limit. 
	Papers must include information on methods, tool availability, maturity,
	selected experimental results.
	Authors should make their tools and benchmarks available at the time of submission for evaluation by the <a href="organization.html#tool_eval"><strong>committee</strong></a>.

	Each submission must be accompanied by a supplementary PDF file illustrating the usage of the tool (e.g. screenshots, step-by-step guide, short tutorial) and, if applicable, how the tool demo will be conducted during the conference presentation. 
	Presenters of accepted tool papers will be encouraged to include a showcase/running demo of the tool in their talk.

<!-- CMSB 2016 will give also one IEEE TCSIM Best Poster award:
<ul>
<li>The Best Poster Award recipient is given public recognition 
and receives an award of 300 US$ from the IEEE Technical Committee 
on Simulation (TCSIM).</li>
</ul> -->

<h2>Important dates</h2>
<ul>
	<li><strong>Abstract presubmission:</strong> <del>April 15, 2016</del></li>
	<li><strong>Paper submission:</strong> <del>April 22, 2016</del> <span class="text-success"><del>May 6, 2016</del></span> </li>
	<li><strong>Paper Notification:</strong> <del>June 10, 2016</del> <span class="text-success"><del>June 17, 2016</del></span> </li>
	<li><strong>Camera-ready:</strong> <del>June 25, 2016</del> <span class="text-success"><del>July 1, 2016</del></span></li>
</ul>
<!-- <table class="table" style="width: auto;">
<tr><td>Abstract pre-submission:</td><td>April 15, 2016</td></tr>
<tr><td>Paper submission:</td><td>April 22, 2016</td></tr>
<tr><td>Poster Submission:</td><td>June 1, 2016</td></tr>
<tr><td>Poster/Paper Notification:</td><td>June 10, 2016</td></tr>
<tr><td>Camera-ready:</td><td>June 25, 2016</td></tr>
</table> -->

<div class="well">
	<h2 style="text-align:center">Awards</h2>
	CMSB 2016 will assign two best paper awards: 
	one IEEE TCSIM Best Student Paper Award and 
	one NVIDIA Best Paper Award.
	<ul>
		<li>The <strong>Best Student Paper Award</strong> recipient is given public recognition and receives an award of 500 USD from the <a href="https://www.computer.org/web/tcsim/index">IEEE Technical Committee on Simulation (TCSIM)</a>. For a paper to qualify for the Best Student Paper Award, a student must be the lead author, the submission must be done in the student paper category and the student must present the paper at the conference.</li>

		<li>The <a href="http://www.nvidia.it/page/home.html">NVIDIA</a> <strong>Best Paper Award</strong> recipient is given public recognition and receives one high end Tesla K40 GPU equipment of a value of 3,200 USD donated by NVIDIA. Any paper on any topic of CMSB can qualify for this award. </li>
	</ul>
</div>

</div>
</div>
