<div class="panel panel-default">
	<div class="panel-body">
		<h1 style="text-align:center">Call for Posters</h1>
		<h2>Topics</h2>
		<p>CMSB 2016 solicits poster abstracts on the analysis of biological systems, networks, data, and corresponding application domains. The conference brings together computer scientists, biologists, mathematicians, engineers, and physicists interested in a system-level understanding of biological processes.</p>
		<ul>
			<li>Topics of interest include, but are not limited to:</li>
			<li><span>formalisms for modelling biological processes,</span></li>
			<li>models and their biological applications,</li>
			<li>frameworks for model verification, validation, analysis and simulation of <span>biological systems,</span></li>
			<li>high-performance computational systems biology and parallel <span>implementations,</span></li>
			<li>model inference from experimental data,</li>
			<li>model integration from biological databases,</li>
			<li>multi-scale modelling and analysis methods,</li>
			<li>methods for synthetic biology and biomolecular computing.</li>
		</ul>

		<h2>Format</h2>
		<div>Poster abstracts must conform the LNCS style (instructions for authors with LaTeX and Word styles can be found here). They have to be submitted electronically as PDF files via EasyChair. <strong>The limit for submissions is 2 pages</strong>.</div>


		<p><a class="btn btn-warning">Submissions are now closed</a></p>

		<h2>Important dates</h2>
		<ul>
			<li><strong>Poster submission:</strong> <del>June 1, 2016</del> <span class="text-success"><del>June 8, 2016</del></span></li>
			<li><strong>Poster Notification:</strong> <del>June 10, 2016</del> <span class="text-success"><del>June 17, 2016</del></span></li>
			<li><strong>Camera-ready:</strong> <del>June 25, 2016</del> <span class="text-success"><del>July 1, 2016</del></span></li>
		</ul>

		<div class="well">
			<h2 style="text-align:center">Awards</h2>
			CMSB 2016 will assign a IEEE TCSIM Best Poster award:
			<ul>
				<li>The <strong>Best Poster Award</strong> recipient is given public recognition 
					and receives an award of 300 USD from the <a href="https://www.computer.org/web/tcsim/index">IEEE Technical Committee on Simulation (TCSIM)</a>.</li>
				</ul>
			</div>

		</div>
	</div>