<div class="panel panel-default">
  <div class="panel-body">
<h1>Call for Papers</h1>
<h2>Topics</h2>
<p>CMSB 2016 solicits original research articles on the analysis of biological systems, networks, data, and corresponding application domains. The conference brings together computer scientists, biologists, mathematicians, engineers, and physicists interested in a system-level understanding of biological processes.</p>
<p>Topics of interest include, but are not limited to:</p>
<ul>
<li>formalisms for modelling biological processes,</li>
<li>models and their biological applications,</li>
<li>frameworks for model verification, validation, analysis and simulation of biological systems,</li>
<li>high-performance computational systems biology and parallelimplementations,</li>
<li>model inference from experimental data,</li>
<li>model integration from biological databases,</li>
<li>multi-scale modelling and analysis methods,</li>
<li>methods for synthetic biology and biomolecular computing.</li>
</ul>
<p>Papers should be submitted to one of the following categories:</p>
<ul>
<!--li>Theory</li>
<li>High performance methods</li>
<li>Tools</li>
<li>Case studies (applications of systems biology methods to real cases or new open questions in biology that require a systems biology approach)</li-->
<li>Regular papers</li>
<li>Tool papers</li>
</ul>

<p class="text-info">Proceedings of CMSB 2016 will be published as a volume in <strong>Springer's Lecture Notes in Computer Science / Lecture Notes in Bioinformatics series (LNCS/LNBI).</strong></p4>
<p>Publication of a selection of the papers in a special issue of a journal is under consideration.</p>
<!--p><a href="https://easychair.org/conferences/?conf=cmsb2016">Click here to submit to easychair.</a></p-->
<p><a href="https://easychair.org/conferences/?conf=cmsb2016" class="btn btn-info">Submit a paper to CMSB2016 now!</a></p>

<h2>Format for regular papers</h2>
Regular papers should describe original work that has not been previously published and is not under review for publication elsewhere. Papers must be written in English and must conform the LNCS style (instructions for authors with LaTeX and Word styles can be found <a href="http://www.springer.com/computer/lncs?SGWID=0-164-6-793341-0">here</a>). They have to be submitted electronically as PDF files via EasyChair. <strong>The limit for submissions is 12 pages</strong>. Appendices will not not be counted in the page limit.

<h2>Format and guidelines for tool papers</h2>
Tool papers should present new tools, new tool components or novel
extensions to existing tools supporting the modelling and analysis of biological systems. Each
submission should be original and not published previously in a tool
paper form.

Papers must be written in English and must conform the LNCS style (instructions for authors with LaTeX and Word styles can be found <a href="http://www.springer.com/computer/lncs?SGWID=0-164-6-793341-0">here</a>). They have to be submitted electronically as PDF files via EasyChair. <strong>The limit for submissions is 6 pages</strong>. Appendices will not not be counted in the page limit. 
Papers must include information on methods, tool availability, maturity,
selected experimental results.
Authors should make their tools and benchmarks available at the time of submission for evaluation by the <a href="organization.html#tool_eval"><strong>committee</strong></a>.

Each submission must be accompanied by a supplementary PDF file illustrating the usage of the tool (e.g. screenshots, step-by-step guide, short tutorial) and, if applicable, how the tool demo will be conducted during the conference presentation. 
Presenters of accepted tool papers will be encouraged to include a showcase/running demo of the tool in their talk.

<h2>Awards</h2>
<!--There will be an award for <strong>Best Paper</strong> and a cash prize of $500 USD for the <strong>Best Student Paper</strong>. The criteria for a Student paper are that the leading (corresponding) author should be registered for a Masters or PhD, and the contributions and percentages of effort by all authors should be clearly stated in an additional section, outside the 20pp limit, which clearly indicates that the submission is in this category. The cash prize is donated by TCSIM - the IEEE Technical Committee on Simulation.-->
There will be awards for Best Paper and Best Student Paper. More details to come.

<h2>Important dates</h2>
<ul>
<li>Abstract submission: April 15, 2016</li>
<li>Paper submission: April 22, 2016</li>
<li>Paper Notification: June 10, 2016</li>
<li>Camera-ready: June 25, 2016</li>
</ul>
</div>
</div>
