<div class="panel panel-default">
	<div class="panel-body">
		<h1 style="text-align:center">Important dates</h1>
		<h2>Regular and tool papers</h2>
		<ul>
			<li><del><strong>Abstract presubmission:</strong> April 15, 2016</del></li>
			<li><strong>Paper submission:</strong> <del>April 22, 2016</del> <span class="text-success">May 6, 2016</span> </li>
			<li><strong>Paper Notification:</strong> <del>June 10, 2016</del> <span class="text-success">June 17, 2016</span> </li>
			<li><strong>Camera-ready:</strong> <del>June 25, 2016</del> <span class="text-success">July 1, 2016</span></li>
		</ul>

		<h2>Poster abstracts</h2>
		<ul>
			<li><strong>Poster submission:</strong> <del>June 1, 2016</del> <span class="text-success">June 8, 2016</span></li>
			<li><strong>Poster Notification:</strong> <del>June 10, 2016</del> <span class="text-success">June 17, 2016</span></li>
			<li><strong>Camera-ready:</strong> <del>June 25, 2016</del> <span class="text-success">July 1, 2016</span></li>
		</ul>
	</div>
</div>
