<div class="panel panel-default">
<div class="panel-body">
<h1>Important dates</h1>
<h2>Regular and tool papers</h2>
<ul>
<li>Abstract presubmission: April 15, 2016</li>
<li>Paper submission: April 22, 2016</li>
<li>Paper Notification: June 10, 2016</li>
<li>Camera-ready: June 25, 2016</li>
</ul>

<h2>Poster abstracts</h2>
TBA
<!--ul>
<li>Abstract submission: April 15, 2016</li>
<li>Paper submission: April 22, 2016</li>
<li>Paper Notification: June 10, 2016</li>
<li>Camera-ready: June 25, 2016</li>
</ul-->