<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>CMSB 2016</title>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <img src='images/CMSB2016-1.jpg' class="img-responsive">
    <div class='container'>
    <div class='row'>
          <div id="navbar" class='col-md-2 sidebar'>
            <ul class='nav nav-sidebar'>
              <li> <a href="index.html">Home</a> </li>
              <li> <a href="organization.html">Organisation</a> </li>
              <li> <a href="registration.html">Registration</a> </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Calls <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li> <a href="call_papers.html">Call for papers</a> </li>
                  <li> <a href="call_posters.html">Call for posters</a> </li>
                </ul>
              </li>
              <li> <a href="calendar.html">Calendar</a> </li>
              <li> <a href="venue.html">Venue</a> </li>
              <li> <a href="contact.html">Contact</a> </li>
            </ul>
          </div>
      <div class='col-md-10 main'>