<div class="row">
	<div class="col-lg-9">

		<div class="well">
			<h2>About</h2>
			<p class="just">The 14th conference on Computational Methods in Systems Biology (CMSB2016) will take place on the <strong>21st to 23rd September 2016</strong> in Cambridge. Its aim is to bring together researchers from across biological, mathematical, computational and physical sciences who are interested in the study and modelling of biological systems.</p>
			<!--p>CMSB2016 is organised by <strong>Pietro Lió</strong> at <strong>Cambridge University Computer Laboratory</strong>.</p-->
			<p>CMSB2016 will be hosted at <strong>Cambridge University Computer Laboratory</strong>.</p>

			<!--p><a class="internal-link" href="resolveuid/5a37bbe871ea4e1bbc0bef93cb2b6fec" target="_self" title="">Register to CMSB2016 now!</a></p-->
			<!--LET'S TRY WITH A BUTTON-->
			<p><a href="call_papers.html" class="btn btn-info">Call for Papers</a></p>
			<!-- <p><a href="registration.html" class="btn btn-info">Register to CMSB2016 now!</a></p> -->
		</div>

		<div class="panel panel-default">
  			<div class="panel-body">
				<h2>Updates</h2>
				<ul>
					<li>Sept 18th 2015: <a class="external-link" href="http://cmsb2015.sciencesconf.org/" target="_self" title="">CMSB 2015</a> finishes</li>
				</ul>
			</div>
		</div>
	</div>

	<div class="col-lg-3">
		<div class="panel panel-default">
  			<div class="panel-body" style="text-align:center">
  				<h4>Download flyer:</h4>	
  				<a href="files/CMSB16_flyer.pdf"><img src = "images/poster_preview.png" alt = "CMSB 2016 poster" width="200px" style = "padding:10px;"/></a>
			</div>
		</div>
  				<!--h4>Sponsored by:</h4>	
				<img src = "images/lncs-300x111.jpg" alt = "Springer LNBI" width="200px" style = "padding:10px;"/>
				<img src = "images/lncs-300x111.jpg" alt = "Springer LNBI" width="200px" style = "padding:10px;"/>
				<img src = "images/lncs-300x111.jpg" alt = "Springer LNBI" width="200px" style = "padding:10px;"/>
		
				<br/><br/-->
  		<div class="panel panel-default">
  			<div class="panel-body" style="text-align:center">
  				<h4>Proceedings in:</h4>
				<img src = "images/lncs-300x111.jpg" alt = "Springer LNBI" width="200px" style = "padding:10px;"/>
			</div>
		</div>
	</div>

</div>
