<div class="row">
	<div class="col-lg-9">
		<div class="well">
			<h2 style="text-align:center">About</h2>
			<p class="just">The 14th conference on Computational Methods in Systems Biology (CMSB2016) will take place on the <strong>21st to 23rd September 2016</strong> in Cambridge. Its aim is to bring together researchers from across biological, mathematical, computational and physical sciences who are interested in the study and modelling of biological systems.</p>
			<!--p>CMSB2016 is organised by <strong>Pietro Lió</strong> at <strong>Cambridge University Computer Laboratory</strong>.</p-->
			<p>CMSB2016 will be hosted at <strong>Cambridge University Computer Laboratory</strong>.</p>

			<!--p><a class="internal-link" href="resolveuid/5a37bbe871ea4e1bbc0bef93cb2b6fec" target="_self" title="">Register to CMSB2016 now!</a></p-->
			<!--LET'S TRY WITH A BUTTON-->
			<p><a href="call_papers.html" class="btn btn-info">Call for Papers</a></p>
			<!-- <p><a href="registration.html" class="btn btn-info">Register to CMSB2016 now!</a></p> -->
		</div>
		<div class="panel panel-default">
			<div class="panel-body">
				<h2 style="text-align:center">Updates</h2>
				<ul class="just">
					<li>18 Mar 2016: Check out CMSB <a class="external-link" href="https://twitter.com/cmsb_2016" target="_self" title="">Twitter</a> and <a class="external-link" href="https://www.facebook.com/CMSB-2016-1062313160503375/" target="_self" title="">Facebook</a> pages!
					</li>

					<li>16 Mar 2016: Second <a class="external-link" href="call_papers.html" target="_self" title="">call for papers</a> and <a class="external-link" href="call_posters.html" target="_self" title="">call for posters</a> published.
					</li>	

					<li>23 Feb 2016: Special issue on <a class="external-link" href="https://www.computer.org/web/tcbb" target="_self" title="">IEEE/ACM Transactions on Computational Biology and Bioinformatics</a> announced (see <a class="external-link" href="call_papers.html" target="_self" title="">call for papers</a>).
					</li>	

					<li>15 Feb 2016: <strong>Awards!!!</strong> Best paper award sponsored by <a href="http://www.nvidia.com/">NVIDIA</a>. Best student paper and Best poster awards sponsored by <a href="https://www.computer.org/web/tcsim/index">IEEE Technical Committee on Simulation</a> (see <a class="external-link" href="call_papers.html" target="_self" title="">call for papers</a> and <a class="external-link" href="call_posters.html" target="_self" title="">call for posters</a>).
					</li>	
				</ul>
				
				<a class="btn btn-primary btn-xs" data-toggle="collapse" data-target=".oldnews">Show/hide older news</a>
				
				<ul class="just collapse oldnews">
					<li>17 Dec 2015: First <a class="external-link" href="call_papers.html" target="_self" title="">call for papers</a> and list of <a class="external-link" href="invited.html" target="_self" title="">invited speakers</a> published</li>			
					<li>18 Sep 2015: <a class="external-link" href="http://cmsb2015.sciencesconf.org/" target="_self" title="">CMSB 2015</a> finishes.</li>
				</ul>


			</div>
		</div>

		<div class="panel panel-default">
			<div class="panel-body">
				<h2 style="text-align:center">Sponsors</h2>
				<div class = "col-sm-6 centered">
					<a href="http://www.nvidia.com/"><img src = "images/logo_nvidia.png" alt = "Nvidia logo" height="100px"/><a/>
					</div>
					<div class = "col-sm-6 centered">
						<a href="https://www.computer.org/web/tcsim/index"><img src = "images/ieee_mb_blue_1.gif" alt = "IEEE logo" height="70px"/></a>
						<br/>
						<h4>Technical Committee on Simulation</h4>
					</div>
				</div>
			</div>
		</div>

		<div class="col-lg-3">
			<div class="panel panel-default">
				<div class="panel-body" style="text-align:center">
					<h4>Download flyer:</h4>	
					<a href="files/CMSB16_flyer.pdf"><img src = "images/poster_preview.png" alt = "CMSB 2016 poster" width="200px" style = "padding:10px;"/></a>
				</div>
			</div>

			<div class="panel panel-default">
				<div class="panel-body" style="text-align:center">
					<h4>Proceedings in:</h4>
					<img src = "images/lncs-300x111.jpg" alt = "Springer LNBI" width="200px" style = "padding:10px;"/>
				</div>
			</div>

			<div class="panel panel-default">
				<div class="panel-body" style="text-align:center">
					<h4>Follow us:</h4>
					<a href="https://twitter.com/cmsb_2016" style = "padding:20px;"><img src = "https://g.twimg.com/Twitter_logo_blue.png" alt = "Twitter logo" height="50px"/></a> 
					<a href="https://www.facebook.com/CMSB-2016-1062313160503375/" style = "padding:20px;"><img src = "https://www.facebookbrand.com/img/fb-art.jpg" alt = "Facebook logo" height="50px"/></a>
					<br/><br/>
					<a class="twitter-timeline" href="https://twitter.com/cmsb_2016" data-widget-id="712333438884442112">Tweets by @cmsb_2016</a>
					<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

				</div>
			</div>

		</div>
	</div>






</div>

</div>
