<div class="panel panel-default">
  <div class="panel-body">
<h1 style="text-align:center">Invited speakers </h1>
<div class = "row">
   <div class = "col-sm-6">
      <div class = "thumbnail">
         <img src = "images/luca.jpg" alt = "Luca Cardelli" height="200" width="200"/>
         <div class="span4 collapse-group">
          <h3 class="centered">Luca Cardelli</h3>
          <h4 class="centered"><strong>Title:</strong> TBA</h4>
           <p class="collapse just" id="invited1"><strong>Abstract:</strong> TBA</p>
           <p class="collapse just" id="invited1_bio"><strong>Bio:</strong> 
           Luca Cardelli has a Ph.D. in computer science from the University of Edinburgh. 
           He worked at Bell Labs, Murray Hill, from 1982 to 1985, and at Digital Equipment Corporation, 
           Systems Research Center in Palo Alto, from 1985 to 1997, before assuming a position at Microsoft Research, 
           in Cambridge UK, where he was head of the Programming Principles and Tools and Security groups until 2012. 
           Since 2014 he is also a Royal Society Research Professor at the University of Oxford.
		   His main interests are in programming languages and concurrency, and more recently in programmable biology 
		   and nanotechnology. He is a Fellow of the Royal Society, a Fellow of the Association for Computing Machinery, 
		   an Elected Member of the Academia Europaea, and an Elected Member of the Association Internationale pour les 
		   Technologies Objets.</p>

          <p class="centered"><a class="btn btn-primary btn-xs" data-toggle="collapse" data-target="#invited1">Show/hide abstract</a>
          <a class="btn btn-primary btn-xs" data-toggle="collapse" data-target="#invited1_bio">Show/hide bio</a></p>
        </div>
      </div>
	</div>
	
	   <div class = "col-sm-6">
      <div class = "thumbnail">
         <img src = "images/joelle_small.png" alt = "Joelle Despeyroux" height="200" width="200"/>
         <div class="span4 collapse-group">
          <h3 class="centered">Joelle Despeyroux</h3>
          <h4 class="centered"><strong>Title:</strong> TBA</h4>
           <p class="collapse just" id="invited2"><strong>Abstract:</strong> TBA</p>
           <p class="collapse just" id="invited2_bio"><strong>Bio:</strong> </p>

          <p class="centered"><a class="btn btn-primary btn-xs" data-toggle="collapse" data-target="#invited2">Show/hide abstract</a>
          <a class="btn btn-primary btn-xs" data-toggle="collapse" data-target="#invited2_bio">Show/hide bio</a></p>
        </div>
      </div>
 		
	</div>
	
	
   <div class = "col-sm-6">
      <div class = "thumbnail">
         <img src = "images/radu.png" alt = "Radu Grosu" height="200" width="200"/>
         <div class="span4 collapse-group">
          <h3 class="centered">Radu Grosu</h3>
          <h4 class="centered"><strong>Title:</strong> TBA</h4>
           <p class="collapse just" id="invited3"><strong>Abstract:</strong> TBA</p>
           <p class="collapse just" id="invited3_bio"><strong>Bio:</strong>
           Radu Grosu is a Professor and Head of the Dependable-Systems Group at
the Faculty of Informatics of the Vienna University of Technology, and
a Research Professor at the Computer Science Department of the State
University of New York at Stony Brook. His research interests include
modeling, analysis and control of cyber-physical and biological
systems and his application focus includes green operating systems,
mobile ad-hoc networks, automotive systems, the Mars rover,
cardiac-cell networks and genetic regulatory networks. Grosu is the
recipient of the National Science Foundation Career Award, the State
University of New York Research Foundation Promising Inventor Award,
the ACM Service Award, and a member of the International Federation of
Information Processing WG 2.2. Before receiving his appointment at the
Vienna University of Technology, Grosu was an Associate Professor in
the Computer Science Department of the State University of New York at
Stony Brook, where he co- directed the Concurrent-Systems laboratory
and co-founded the Systems-Biology laboratory. Grosu earned his
Dr.rer.nat. in Computer Science from the Technical University of
Munchen, and was a Research Associate in the Computer Science
Department of the University of Pennsylvania.</p>

          <p class="centered"><a class="btn btn-primary btn-xs" data-toggle="collapse" data-target="#invited3">Show/hide abstract</a>
          <a class="btn btn-primary btn-xs" data-toggle="collapse" data-target="#invited3_bio">Show/hide bio</a></p>
        </div>
      </div>
	</div>
   <div class = "col-sm-6">
      <div class = "thumbnail">
         <img src = "images/Jane_Hillston.jpg" alt = "Jane Hillston" height="200" width="200"/>
         <div class="span4 collapse-group">
          <h3 class="centered">Jane Hillston</h3>
          <h4 class="centered"><strong>Title:</strong> TBA</h4>
           <p class="collapse just" id="invited4"><strong>Abstract:</strong> TBA</p>
           <p class="collapse just" id="invited4_bio"><strong>Bio:</strong> </p>

          <p class="centered"><a class="btn btn-primary btn-xs" data-toggle="collapse" data-target="#invited4">Show/hide abstract</a>
          <a class="btn btn-primary btn-xs" data-toggle="collapse" data-target="#invited4_bio">Show/hide bio</a></p>
        </div>
      </div>
 		
	</div>
	
	

</div>
</div></div>
