<div class="panel panel-default">
  <div class="panel-body">
<h1>Invited speakers </h1>
More to come...
<div class = "row">
   <!-- uncomment with more than 2 invited speakers div class = "col-sm-4"-->
   <div class = "col-sm-6">
      <div class = "thumbnail">
         <img src = "images/radu.png" alt = "Radu Grosu" height="200" width="200">
         <div class="span4 collapse-group">
          <h2>Radu Grosu<h2>
          <h3><strong>Title:</strong> TBA</h3>
           <p class="collapse" id="invited1"><strong>Abstract:</strong> TBA</p>
           <p class="collapse" id="invited1_bio"><strong>Bio:</strong>....</p>

          <p><a class="btn btn-primary btn-xs" data-toggle="collapse" data-target="#invited1">Show/hide abstract</a>
          <a class="btn btn-primary btn-xs" data-toggle="collapse" data-target="#invited1_bio">Show/hide bio</a></p>
        </div>
      </div>
	</div>
   <div class = "col-sm-6">
      <div class = "thumbnail">
         <img src = "images/Jane_Hillston.jpg" alt = "Jane Hillston" height="200" width="200">
         <div class="span4 collapse-group">
          <h2>Jane Hillston<h2>
          <h3><strong>Title:</strong> TBA</h3>
           <p class="collapse" id="invited2"><strong>Abstract:</strong> TBA</p>
           <p class="collapse" id="invited2_bio"><strong>Bio:</strong> </p>

          <p><a class="btn btn-primary btn-xs" data-toggle="collapse" data-target="#invited2">Show/hide abstract</a>
          <a class="btn btn-primary btn-xs" data-toggle="collapse" data-target="#invited2_bio">Show/hide bio</a></p>
        </div>
      </div>
 		
	</div>
   <!--div class = "col-sm-4">
      <div class = "thumbnail">
         <img src = "images/kittens.jpg" alt = "AUTHOR NAME GOES HERE">
      </div>
 		<div class="span4 collapse-group">
          <h2>AUTHOR NAME GOES HERE<h2>
          <h3>TITLE GOES HERE</h3>
           <p class="collapse" id="invited3">ABSTRACT GOES HERE. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-primary btn-xs" data-toggle="collapse" data-target="#invited3">Show/hide abstract</a></p>
        </div>
	</div>
   <div class = "col-sm-4">
      <div class = "thumbnail">
         <img src = "images/kittens.jpg" alt = "AUTHOR NAME GOES HERE">
      </div>
 		<div class="span4 collapse-group">
          <h2>AUTHOR NAME GOES HERE<h2>
          <h3>TITLE GOES HERE</h3>
           <p class="collapse" id="invited4">ABSTRACT GOES HERE. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-primary btn-xs" data-toggle="collapse" data-target="#invited4">Show/hide abstract</a></p>
        </div>
	</div>
   <div class = "col-sm-4">
      <div class = "thumbnail">
         <img src = "images/kittens.jpg" alt = "AUTHOR NAME GOES HERE">
      </div>
 		<div class="span4 collapse-group">
          <h2>AUTHOR NAME GOES HERE<h2>
          <h3>TITLE GOES HERE</h3>
           <p class="collapse" id="invited5">ABSTRACT GOES HERE. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-primary btn-xs" data-toggle="collapse" data-target="#invited5">Show/hide abstract</a></p>
        </div>
	</div-->
</div>
</div></div>
