<h1>Organization</h1>
<h2>Committees</h2>

<h3>Steering Commitee</h3>
<ul>
<li>Finn Drablos - NTNU, Norway</li>
<li>Francois Fages - INRIA Paris Rocquencourt, France</li>
<li>David Harel - Weizmann Institute of Science, Israel</li>
<li>Monika Heiner - Brandenburg University of Technology, Cottbus, Germany</li>
<li>Tommaso Mazza - IRCCS Casa Sollievo della Sofferenza - Mendel, Italy</li>
<li>Satoru Miyano - University of Tokyo, Japan</li>
<li>Gordon Plotkin - University of Edinburgh, UK</li>
<li>Corrado Priami - CoSBi / Microsoft Research, University of Trento, Italy</li>
<li>Carolyn Talcott - Stanford Research Institute, USA </li>
<li>Adelinde Uhrmacher - University of Rostock, Germany</li>
</ul>

<h3>Organizing Committee</h3>
<ul>
<li>PC Chair: Pietro Lio', Computer Laboratory, University of Cambridge</li>
<li>PC co-Chair: Ezio Bartocci, TU Wien</li>
<li>PC co-Chair: Nicola Paoletti, Department of Computer Science, University of Oxford</li>
<li>Publicity Chair: Claudio Angione, School of Computing, Teesside University</li>
<li>Local organisation Chair: Max Conway, Computer Laboratory, University of Cambridge</li>

</ul>

<h3>Program Committee (Tentitative)</h3>
<ul>
<li>Julio Banga, IIM-CSIC</li>
<li>Ezio Bartocci, TU Wien</li>
<li>Gregory Batt, INRIA Paris-Rocquencourt</li>
<li>Luca Bortolussi, University of Trieste</li>
<li>Jeremie Bourdon, LINA, CNRS UMR6241, Nantes University</li>
<li>Luca Cardelli, Microsoft Research</li>
<li>Joelle Despeyroux, INRIA</li>
<li>Diego Di Bernardo, </li>
<li>François Fages, Inria Paris-Rocquencourt</li>
<li>Flavio H Fenton, Cornell University, Ithaca, US</li>
<li>Jerome Feret, INRIA / Ecole normale supérieure</li>
<li>Calin Guet, IST</li>
<li>Monika Heiner, Brandenburg University at Cottbus</li>
<li>Heinz Koeppl, Technische Universitat Darmstadt</li>
<li>Hillel Kugler, Microsoft Research</li>
<li>Marta Kwiatkowska, University of Oxford</li>
<li>Pietro Lio', Computer Laboratory, University of Cambridge</li>
<li>Pedro Mendes, School of Computer Science, The University of Manchester; Center for Quantitative Medicine, University of Connecticut Health Center</li>
<li>Nicola Paoletti, Department of Computer Science, University of Oxford</li>
<li>Tatjana Petrov, IST Austria</li>
<li>Andrew Phillips, Microsoft Research</li>
<li>Carla Piazza, University of Udine</li>
<li>Ovidiu Radulescu, University of Montpellier 2</li>
<li>Olivier Roux, IRCCyN</li>
<li>David Šafránek, Masaryk University</li>
<li>Guido Sanguinetti, University of Edinburgh</li>
<li>Joerg Stelling, ETH Zurich</li>
<li>Carolyn Talcott, SRI International</li>
<li>P S Thiagarajan, National University of Singapore</li>
<li>Adelinde Uhrmacher, Universitt Rostock</li>
<li>Verena Wolf, Saarland University</li>
<li>Boyan Yordanov, Microsoft Research</li>
<li>Paolo Zuliani, Newcastle University</li>
</ul>

<h2>Past CMSB Events</h2>
<ul>
<li><a class="external-link" href="http://cmsb2015.sciencesconf.org/" target="_self" title="">CMSB 2015</a>, Nantes, France</li>
<li><a href="http://www.comp-sys-bio.org/CMSB14" target="_blank">CMSB 2014</a> Manchester, UK,</li>
<li><a href="http://ist.ac.at/cmsb13" target="_blank">CMSB 2013</a> Klosterneuburg, Austria,</li>
<li><a href="http://sites.brunel.ac.uk/cmsb2012" target="_blank">CMSB 2012</a> London, UK,</li>
<li><a href="http://contraintes.inria.fr/CMSB11/" target="_blank">CMSB 2011</a> Paris, France,</li>
<li><a href="http://www.cosbi.eu/cmsb2010" target="_blank">CMSB 2010</a> Trento, Italy,</li>
<li><a href="http://www.cmsb09.cs.unibo.it/" target="_blank">CMSB 2009</a> Bologna, Italy,</li>
<li><a href="http://wwwmosi.informatik.uni-rostock.de/cmsb08/" target="_blank">CMSB 2008</a> Rostock, Germany,</li>
<li><a href="http://conferences.inf.ed.ac.uk/cmsb07/index.html" target="_blank">CMSB 2007</a> Edinburgh, UK,</li>
<li><a href="http://www.cosbi.eu/index.php/topic-cmsb/" target="_blank">CMSB 2006</a> Trento, Italy,</li>
<li><a href="http://web.archive.org/web/20060109002039/http:/homepages.inf.ed.ac.uk/v1bklin/cmsb05/" target="_blank">CMSB 2005</a> Edinburgh, UK,</li>
<li><a href="http://www.informatik.uni-trier.de/%7Eley/db/conf/cmsb/cmsb2004.html" target="_blank">CMSB 2004</a> Paris, France,</li>
<li><a href="http://www.informatik.uni-trier.de/%7Eley/db/conf/cmsb/cmsb2003.html" target="_blank">CMSB 2003</a> Rovereto, Italy.</li>
</ul>