<h1>Organisation</h1>
<!--h2>Committees</h2-->

<h3>PC co-Chairs</h3>
<ul>
<li><a href="http://www.eziobartocci.com/">Ezio Bartocci</a>, TU Wien (Austria)</li>
<li><a href="https://www.cl.cam.ac.uk/~pl219/">Pietro Lio'</a>, University of Cambridge (UK)</li>
<li><a href="https://www.cs.ox.ac.uk/people/nicola.paoletti/">Nicola Paoletti</a>, University of Oxford (UK)</li>
</ul>
<h3>Tool Track Chair</h3>
<ul>
<li><a href="https://www.scm.tees.ac.uk/c.angione/">Claudio Angione</a>, Teesside University (UK)</li>
</ul>
<h3>Local Organisation Chair</h3>
<ul>
<li>Max Conway, University of Cambridge (UK)</li>
</ul>

<h3>Program Committee</h3>
<ul>
<li><a href="https://www.scm.tees.ac.uk/c.angione/">Claudio Angione</a>, Teesside University (UK)</li>
<li><a href="http://gingproc.iim.csic.es/~julio/index.html">Julio Banga</a>, IIM-CSIC (Spain)</li>
<li><a href="http://www.eziobartocci.com/">Ezio Bartocci</a>, TU Wien (Austria)</li>
<li><a href="https://contraintes.inria.fr/~batt/home.html">Gregory Batt</a>, INRIA Paris-Rocquencourt (France)</li>
<li><a href="http://www.bortolussi.dmg.units.it">Luca Bortolussi</a>, University of Trieste (Italy)</li>
<li><a href="http://jeremiebourdon.free.fr/wiki.php/Accueil">Jeremie Bourdon</a>, Université de Nantes (France)</li>
<li><a href="http://lucacardelli.name">Luca Cardelli</a>, Microsoft Research Cambridge (UK)</li>
<li><a href="https://www.cs.ox.ac.uk/people/milan.ceska/">Milan Ceska</a>, University of Oxford (UK)</li>
<li><a href="http://homepages.inf.ed.ac.uk/vdanos/home_page.html">Vincent Danos</a>, University of Edinburgh (UK)</li>
<li><a href="http://www-sop.inria.fr/members/Joelle.Despeyroux/">Joelle Despeyroux</a>, INRIA Sophia Antipolis (France)</li>
<li><a href="http://dibernardo.tigem.it">Diego Di Bernardo</a>, University of Naples Federico II (Italy)</li> 
<li><a href="http://lifeware.inria.fr/wiki/Fages/HomePage">François Fages</a>, INRIA Paris-Rocquencourt (France)</li>
<li><a href="http://thevirtualheart.org/FentonCherry/fenton.html">Flavio H Fenton</a>, Georgia Tech (USA)</li>
<li><a href="http://www.di.ens.fr/~feret/">Jerome Feret</a>, INRIA / Ecole normale supérieure (France)</li>
<li><a href="https://ist.ac.at/research/research-groups/guet-group/">Calin Guet</a>, IST Austria (Austria)</li>
<li><a href="http://www-dssz.informatik.tu-cottbus.de/DSSZ/Main/MonikaHeiner">Monika Heiner</a>, Brandenburg University of Technology (Germany)</li>
<li><a href="http://www.csd.uwo.ca/~lila/">Lila Kari</a>, University of Western Ontario (USA)</li>
<li><a href="http://www.bcs.tu-darmstadt.de/biocomm/people_1/professor/heinzkoeppl.en.jsp">Heinz Koeppl</a>, Technische Universitat Darmstadt (Germany)</li>
<li><a href="http://engineering.biu.ac.il/en/node/7019">Hillel Kugler</a>, Bar-Ilan University (Israel)</li>
<li><a href="http://www.cs.ox.ac.uk/marta.kwiatkowska/">Marta Kwiatkowska</a>, University of Oxford (UK)</li>
<li><a href="https://www.cl.cam.ac.uk/~pl219/">Pietro Lio'</a>, University of Cambridge (UK)</li>
<li><a href="http://www-verimag.imag.fr/~maler/">Oded Maler</a>, CNRS-VERIMAG (France)</li>  
<li><a href="http://www.bio.disco.unimib.it/~mauri/">Giancarlo Mauri</a>, University of Milano-Bicocca (Italy)</li>  
<li><a href="http://www.manchester.ac.uk/research/pedro.mendes/">Pedro Mendes</a>, University of Manchester (UK) / University of Connecticut Health Center (USA)</li>
<li><a href="https://www.cs.ox.ac.uk/people/nicola.paoletti/">Nicola Paoletti</a>, University of Oxford (UK)</li>
<li><a href="http://pub.ist.ac.at/~tpetrov/">Tatjana Petrov</a>, IST Austria (Austria)</li>
<li><a href="http://research.microsoft.com/en-us/people/aphillip/">Andrew Phillips</a>, Microsoft Research Cambridge (UK)</li>
<li><a href="https://users.dimi.uniud.it/~carla.piazza/">Carla Piazza</a>, University of Udine (Italy)</li>
<li><a href="http://www.pages-perso-ovidiu-radulescu.univ-montp2.fr/">Ovidiu Radulescu</a>, University of Montpellier 2 (France)</li>
<li><a href="http://www.cs.ox.ac.uk/people/blanca.rodriguez/">Blanca Rodriguez</a>, University of Oxford (UK)</li>
<li><a href="https://olivieroux.wordpress.com/">Olivier Roux</a>, École Centrale de Nantes (France)</li>
<li><a href="http://www.fi.muni.cz/~xsafran1/">David Šafránek</a>, Masaryk University (Czech Republic)</li>
<li><a href="http://homepages.inf.ed.ac.uk/gsanguin/">Guido Sanguinetti</a>, University of Edinburgh (UK)</li>
<li><a href="http://www3.cs.stonybrook.edu/~sas/">Scott A. Smolka</a>, Stony Brook University (USA)</li>
<li><a href="http://www.csb.ethz.ch/">Joerg Stelling</a>, ETH Zurich (Switzerland)</li>
<li><a href="https://www.sri.com/about/people/carolyn-talcott">Carolyn Talcott</a>, SRI International (USA)</li>
<li><a href="http://www.ipal.cnrs.fr/thiagu">P S Thiagarajan</a>, National University of Singapore (Singapore)</li>
<li><a href="http://www.scs.org/uhrmacher">Adelinde Uhrmacher</a>, University of Rostock (Germany)</li>
<li><a href="https://mosi.uni-saarland.de/">Verena Wolf</a>, Saarland University (Germany)</li>
<li><a href="http://research.microsoft.com/en-us/people/yordanov/">Boyan Yordanov</a>, Microsoft Research Cambridge (UK)</li>
<li><a href="https://sites.google.com/site/zupaolo/">Paolo Zuliani</a>, Newcastle University (UK)</li>
</ul>

<h3 id="tool_eval">Tool Evaluation Committee</h3>
<ul>
<li> <a href="https://www.scm.tees.ac.uk/c.angione/">Claudio Angione</a> (<strong>chair</strong>), Teesside University (UK)</li>
<li>...</li>
</ul>

<h3>Steering Committee</h3>
<ul>
<li><a href="http://jeremiebourdon.free.fr/wiki.php/Accueil">Jeremie Bourdon</a>, Université de Nantes (France)</li>
<li><a href="http://folk.ntnu.no/drablos/">Finn Drablos</a> - NTNU (Norway)</li>
<li><a href="http://lifeware.inria.fr/wiki/Fages/HomePage">François Fages</a> - INRIA Saclay Île-de-France (France)</li>
<li><a href="http://www.wisdom.weizmann.ac.il/~harel/">David Harel</a> - Weizmann Institute of Science (Israel)</li>
<li><a href="http://www-dssz.informatik.tu-cottbus.de/DSSZ/Main/MonikaHeiner">Monika Heiner</a> - Brandenburg University of Technology, Cottbus (Germany)</li>
<li><a href="http://www.css-mendel.it/unita-di-ricerca/gruppo-bioinformatica/">Tommaso Mazza</a> - IRCCS Casa Sollievo della Sofferenza - Mendel (Italy)</li>
<li><a href="http://www.manchester.ac.uk/research/pedro.mendes/">Pedro Mendes</a>, University of Manchester (UK) / University of Connecticut Health Center (USA)</li>
<li><a href="http://dnagarden.hgc.jp/miyano/en/doku.php?id=home">Satoru Miyano</a> - University of Tokyo (Japan)</li>
<li><a href="http://homepages.inf.ed.ac.uk/gdp/">Gordon Plotkin</a> - University of Edinburgh (UK)</li>
<li><a href="http://www.cosbi.eu/">Corrado Priami</a> - CoSBi / Microsoft Research, University of Trento (Italy)</li>
<li><a href="https://olivieroux.wordpress.com/">Olivier Roux</a>, École Centrale de Nantes (France)</li>
<li><a href="https://www.sri.com/about/people/carolyn-talcott">Carolyn Talcott</a> - SRI International (USA)</li>
<li><a href="http://www.scs.org/uhrmacher">Adelinde Uhrmacher</a> - University of Rostock (Germany)</li>
</ul>

<h2>Past CMSB Events</h2>
<ul>
<li><a class="external-link" href="http://cmsb2015.sciencesconf.org/" target="_self" title="">CMSB 2015</a> Nantes, France</li>
<li><a href="http://www.comp-sys-bio.org/CMSB14" target="_blank">CMSB 2014</a> Manchester, UK,</li>
<li><a href="http://ist.ac.at/cmsb13" target="_blank">CMSB 2013</a> Klosterneuburg, Austria,</li>
<li><a href="http://sites.brunel.ac.uk/cmsb2012" target="_blank">CMSB 2012</a> London, UK,</li>
<li><a href="http://contraintes.inria.fr/CMSB11/" target="_blank">CMSB 2011</a> Paris, France,</li>
<li><a href="http://www.cosbi.eu/cmsb2010" target="_blank">CMSB 2010</a> Trento, Italy,</li>
<li><a href="http://www.cmsb09.cs.unibo.it/" target="_blank">CMSB 2009</a> Bologna, Italy,</li>
<li><a href="http://wwwmosi.informatik.uni-rostock.de/cmsb08/" target="_blank">CMSB 2008</a> Rostock, Germany,</li>
<li><a href="http://conferences.inf.ed.ac.uk/cmsb07/index.html" target="_blank">CMSB 2007</a> Edinburgh, UK,</li>
<li><a href="http://www.cosbi.eu/index.php/topic-cmsb/" target="_blank">CMSB 2006</a> Trento, Italy,</li>
<li><a href="http://web.archive.org/web/20060109002039/http:/homepages.inf.ed.ac.uk/v1bklin/cmsb05/" target="_blank">CMSB 2005</a> Edinburgh, UK,</li>
<li><a href="http://www.informatik.uni-trier.de/%7Eley/db/conf/cmsb/cmsb2004.html" target="_blank">CMSB 2004</a> Paris, France,</li>
<li><a href="http://www.informatik.uni-trier.de/%7Eley/db/conf/cmsb/cmsb2003.html" target="_blank">CMSB 2003</a> Rovereto, Italy.</li>
</ul>
