<div class="panel panel-default">
	<div class="panel-body">
		<h1 style="text-align:center">Program</h1>
		<h2>Timetable</h2>

		<table class="table table-condensed table-hover table-bordered" style="font-size: 70%">
			<thead>
				<tr>
					<th>Time</th>
					<th>Tue, 20 Sep</th>
					<th>Wed, 21 Sep</th>
					<th>Thu, 22 Sep</th>
					<th>Fri, 23 Sep</th> 
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>09:00-09:30</td>
					<!-- Tue, 20 Sep -->
					<td class="active" rowspan="11"/>
					<!-- Wed, 21 Sep -->
					<td class="warning"><a href="#registration">Registration and welcome</a></td>
					<!-- Thu, 22 Sep -->
					<td rowspan="2" class="info"><a href="#invited3">Invited talk: Luca Cardelli</a></td>
					<!-- Fri, 23 Sep -->
					<td rowspan="2" class="info"><a href="#invited4">Invited talk: Radu Grosu</a></td>
				</tr>
				<tr>
					<td>09:30-10:00</td>
					<!-- Tue, 20 Sep -->
					<!-- Wed, 21 Sep -->
					<td rowspan="2" class="info"><a href="#invited1">Invited talk: Jane Hillston</a></td>
					<!-- Thu, 22 Sep -->
					<!-- Fri, 23 Sep -->
				</tr>
				<tr>
					<td>10:00-10:30</td>
					<!-- Tue, 20 Sep -->
					<!-- Wed, 21 Sep -->
					<!-- Thu, 22 Sep -->
					<td class="warning"><a href="#coffee3">Coffee break</a></td>
					<!-- Fri, 23 Sep -->
					<td class="warning"><a href="#coffee5">Coffee break</a></td>
				</tr>
				<tr>
					<td>10:30-11:00</td>
					<!-- Tue, 20 Sep -->
					<!-- Wed, 21 Sep -->
					<td class="warning"><a href="#coffee1">Coffee break</a></td>
					<!-- Thu, 22 Sep -->
					<td rowspan="2" class="success"><a href="#session_2_1">Session 2.1: Case studies</a></td>
					<!-- Fri, 23 Sep -->
					<td rowspan="3" class="success"><a href="#session_3_1">Session 3.1: Abstraction/Reduction/Approximation</a></td>
				</tr>
				<tr>
					<td>11:00-11:30</td>
					<!-- Tue, 20 Sep -->
					<!-- Wed, 21 Sep -->
					<td rowspan="3" class="success"><a href="#session_1_1">Session 1.1: Estimation/Inference/Synthesis</a></td>
					<!-- Thu, 22 Sep -->
					<!-- Fri, 23 Sep -->
				</tr>
				<tr>
					<td>11:30-12:00</td>
					<!-- Tue, 20 Sep -->
					<!-- Wed, 21 Sep -->
					<!-- Thu, 22 Sep -->
					<td rowspan="2" class="success"><a href="#session_2_2">Session 2.2: Poster flashes</a></td>
					<!-- Fri, 23 Sep -->
				</tr>
				<tr>
					<td>12:00-12:30</td>
					<!-- Tue, 20 Sep -->
					<!-- Wed, 21 Sep -->
					<!-- Thu, 22 Sep -->
					<!-- Fri, 23 Sep -->
					<td rowspan="3" class="warning"><a href="#lunch3">Lunch</a></td>
				</tr>
				<tr>
					<td>12:30-13:00</td>
					<!-- Tue, 20 Sep -->
					<!-- Wed, 21 Sep -->
					<td rowspan="3" class="warning"><a href="#lunch1">Lunch</a></td>
					<!-- Thu, 22 Sep -->
					<td rowspan="3" class="warning"><a href="#lunch2">Lunch + Poster session</a></td>
					<!-- Fri, 23 Sep -->
				</tr>
				<tr>
					<td>13:00-13:30</td>
					<!-- Tue, 20 Sep -->
					<!-- Wed, 21 Sep -->
					<!-- Thu, 22 Sep -->
					<!-- Fri, 23 Sep -->
				</tr>
				<tr>
					<td>13:30-14:00</td>
					<!-- Tue, 20 Sep -->
					<!-- Wed, 21 Sep -->
					<!-- Thu, 22 Sep -->
					<!-- Fri, 23 Sep -->
					<td rowspan="2" class="success"><a href="#session_3_2">Session 3.2: Tools</a></td>
				</tr>
				<tr>
					<td>14:00-14:30</td>					
					<!-- Tue, 20 Sep -->
					<!-- Wed, 21 Sep -->
					<td rowspan="2" class="info"><a href="#invited2">Invited talk: Joelle Despeyroux</a></td>
					<!-- Thu, 22 Sep -->
					<td rowspan="2" class="success"><a href="#session_2_3">Session 2.3: Reaction networks (1)</a></td>
					<!-- Fri, 23 Sep -->
				</tr>
				<tr>
					<td>14:30-15:00</td>
					<!-- Tue, 20 Sep -->
					<td class="danger" rowspan="6"><a href="#workshop">Workshop</a></td>
					<!-- Wed, 21 Sep -->
					<!-- Thu, 22 Sep -->
					<!-- Fri, 23 Sep -->
					<td class="success"><a href="#session_3_3">Session 3.3: Optimisation and control (2)</a></td>
				</tr>
				<tr>
					<td>15:00-15:30</td>
					<!-- Tue, 20 Sep -->
					<!-- Wed, 21 Sep -->
					<td class="warning"><a href="#coffee2">Coffee break</a></td>
					<!-- Thu, 22 Sep -->
					<td class="warning"><a href="#coffee4">Coffee break</a></td>
					<!-- Fri, 23 Sep -->
					<td class="warning"><a href="#closing">Closing</a></td>
					<td rowspan="9" class="active"/>
				</tr>
				<tr>
					<td>15:30-16:00</td>
					<!-- Tue, 20 Sep -->
					<!-- Wed, 21 Sep -->
					<td class="success"><a href="#session_1_2">Session 1.2: Optimisation and control (1)</a></td>
					<!-- Thu, 22 Sep -->
					<td rowspan="3" class="success"><a href="#session_2_4">Session 2.4: Reaction networks (2)</a></td>
					<!-- Fri, 23 Sep -->
				</tr>
				<tr>
					<td>16:00-16:30</td>
					<!-- Tue, 20 Sep -->
					<!-- Wed, 21 Sep -->
					<td rowspan="2" class="success"><a href="#session_1_3">Session 1.3: High-performance methods</a></td>
					<!-- Thu, 22 Sep -->
					<!-- Fri, 23 Sep -->
				</tr>
				<tr>
					<td>16:30-17:00</td>
					<!-- Tue, 20 Sep -->
					<!-- Wed, 21 Sep -->
					<!-- Thu, 22 Sep -->
					<!-- Fri, 23 Sep -->
				</tr>
				<tr>
					<td>17:00-17:30</td>
					<!-- Tue, 20 Sep -->
					<!-- Wed, 21 Sep -->
					<td class="active" rowspan="5"/>
					<!-- Thu, 22 Sep -->
					<td class="warning"><a href="#award_cer">Award ceremony</a></td>
					<!-- Fri, 23 Sep -->
				</tr>
				<tr>
					<td>17:30-18:00</td>
					<!-- Tue, 20 Sep -->
					<td class="active" rowspan="4"/>
					<!-- Wed, 21 Sep -->
					<!-- Thu, 22 Sep -->
					<td rowspan="2" class="warning"><a href="#business_meeting">Business meeting</a></td>
					<!-- Fri, 23 Sep -->
				</tr>
				<tr>
					<td>18:00-18:30</td>
					<!-- Tue, 20 Sep -->
					<!-- Wed, 21 Sep -->
					<!-- Thu, 22 Sep -->
					<!-- Fri, 23 Sep -->
				</tr>
				<tr>
					<td>18:30-19:00</td>
					<!-- Tue, 20 Sep -->
					<!-- Wed, 21 Sep -->
					<!-- Thu, 22 Sep -->
					<td class="active"/>
					<!-- Fri, 23 Sep -->
				</tr>
				<tr>
					<td><br><br>19:00-21:30<br><br></td>
					<!-- Tue, 20 Sep -->
					<!-- Wed, 21 Sep -->
					<!-- Thu, 22 Sep -->
					<td class="warning"><a href="#social_event">Social event and dinner</a></td>
					<!-- Fri, 23 Sep -->
				</tr>
			</tbody>
		</table>


		<br>

		<h2>Social Event: Dinner at Emmanuel College</h2>
		<span id="dinner_emmanuel" class="fixHeaderOffset"></span>
		<div class="row">
			<div class="col-md-5">
				<img src="images/emma_hall.jpg" class="img-responsive">
			</div>
			<div class="col-md-5">
				<p>Dinner on Thursday night will be at <a href="http://www.emma.cam.ac.uk/">Emmanuel College</a>, in central Cambridge. Emmanuel is one of the larger Cambridge colleges, and famed for the quality of its food.</p>
				<p>Additional tickets can be purchased for guests - see the <a href="registration.html">registration</a> page.</p>
				<p>There will be a drinks reception from 19:00, with dinner served at 19:30.</p>
			</div>
		</div>
		<br>

		<h2>Detailed program</h2>
		<h3>Tuesday, 20th September</h3>
		<span id="workshop" class="fixHeaderOffset"></span>
		<ul class="list-group">
			<li class="list-group-item">
				<h4 class="list-group-item-heading">14:30 - 17:30: <a href="workshop.html">Workshop on Automated Reasoning</a></h4>
			</li>
		</ul>

		<h3>Wednesday, 21st September</h3>
		<ul class="list-group">
			<li class="list-group-item"><span id="registration" class="fixHeaderOffset"></span>
				<p class="list-group-item-heading">09:00 - 09:30. Registration and welcome</p>
			</li>
		</ul>

		<ul class="list-group">
			<li class="list-group-item"><span id="invited1" class="fixHeaderOffset"></span>
				<h4 class="list-group-item-heading">09:30 - 10:30. Invited talk: <strong>Jane Hillston</strong>. Chair: Pietro Lio'</h4>
				<span class="papertitle" data-toggle="collapse" data-target="#Invited_hillston">Embedding Machine Learning in Formal Stochastic Models of Biological Processes</span>
				<p class="collapse just list-group-item-text" style="font-size: 90%" id="Invited_hillston"/>
			</li>
		</ul>

		<ul class="list-group">
			<li class="list-group-item"><span id="coffee1" class="fixHeaderOffset"></span>
				<p class="list-group-item-heading">10:30 - 11:00. Coffee break</p>
			</li>
		</ul>

		<ul class="list-group">
			<li class="list-group-item"><span id="session_1_1" class="fixHeaderOffset"></span>
				<h4 class="list-group-item-heading">11:00 - 12:30. Session 1.1: <strong>Estimation, inference and synthesis methods</strong>. Chair: Verena Wolf</h4>
				<ul style="font-size: 90%">
					<li class="list-group-item">
						<span class="authors">Carolin Loos, Anna Fiedler and Jan Hasenauer.</span>
						<span class="papertitle" data-toggle="collapse" data-target="#98590180">Parameter estimation for reaction rate equation constrained mixture models</span>
						<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590180"/>
					</li>

					<li class="list-group-item">
						<span class="authors"><a href="http://www.irccyn.ec-nantes.fr/~benabdal/">Emna Ben Abdallah</a>, <a href="http://tony.research.free.fr/">Tony Ribeiro</a>, <a href="http://www.irccyn.ec-nantes.fr/~magnin/">Morgan Magnin</a>, <a href="http://www.irccyn.ec-nantes.fr/~roux/">Olivier Roux</a> and <a href="http://research.nii.ac.jp/~inoue">Katsumi Inoue</a>.</span>
						<span class="papertitle" data-toggle="collapse" data-target="#98590028">Inference of delayed biological regulatory networks from time series data</span>
						<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590028"/>
					</li>
					<li class="list-group-item">
						<span class="authors"><a href="https://sites.google.com/site/giuliocaravagna/">Giulio Caravagna</a>, <a href="http://bortolussi.dmg.units.it">Luca Bortolussi</a> and Guido Sanguinetti.</span>
						<span class="papertitle" data-toggle="collapse" data-target="#98590048">Matching models across abstraction levels with Gaussian Processes</span>
						<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590048"/>
					</li>
				</ul>
			</li>
		</ul>

		<ul class="list-group">
			<li class="list-group-item"><span id="lunch1" class="fixHeaderOffset"></span>
				<p class="list-group-item-heading">12:30 - 14:00. Lunch</p>
			</li>
		</ul>

		<ul class="list-group">
			<li class="list-group-item"><span id="invited2" class="fixHeaderOffset"></span>
				<h4 class="list-group-item-heading">14:00 - 15:00. Invited talk: <strong>Joelle Despeyroux</strong>. Chair: Carolyn Talcott</h4>
				<span class="papertitle" data-toggle="collapse" data-target="#Invited_despeyroux">(Mathematical) Logic for Systems Biology</span>
				<p class="collapse just list-group-item-text" style="font-size: 90%" id="Invited_despeyroux"/>
			</li>
		</ul>

		<ul class="list-group">
			<li class="list-group-item"><span id="coffee2" class="fixHeaderOffset"></span>
				<p class="list-group-item-heading">15:00 - 15:30. Coffee break</p>
			</li>
		</ul>

		<ul class="list-group">
			<li class="list-group-item"><span id="session_1_2" class="fixHeaderOffset"></span>
				<h4 class="list-group-item-heading">15:30 - 16:00. Session 1.2: <strong>Optimisation and control (1)</strong>. Chair: Ezio Bartocci </h4>
				<ul style="font-size: 90%">

					<li class="list-group-item">
						<span class="authors">Chieh Lo and Radu Marculescu.</span>
						<span class="papertitle" data-toggle="collapse" data-target="#98590163">Autonomous and Adaptive Control of Populations of Bacteria through Environment Regulation</span>
						<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590163"/>
					</li>
				</ul>
			</li>
		</ul>

		<ul class="list-group">
			<li class="list-group-item"><span id="session_1_3" class="fixHeaderOffset"></span>
				<h4 class="list-group-item-heading">16:00 - 17:00. Session 1.3: <strong>High-performance and parallel methods</strong>. Chair: Ezio Bartocci</h4>
				<ul style="font-size: 90%">
					<li class="list-group-item">
						<span class="authors"><a href="http://wwwen.uni.lu/recherche/fstc/computer_science_and_communications_research_unit/members/andrzej_mizera">Andrzej Mizera</a>, <a href="http://satoss.uni.lu/jun">Jun Pang</a> and Qixia Yuan.</span>
						<span class="papertitle" data-toggle="collapse" data-target="#98590210">Fast Simulation of Probabilistic Boolean Networks</span>
						<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590210"/>
					</li>

					<li class="list-group-item">
						<span class="authors">Martin Demko, Nikola Benes, Lubos Brim, Samuel Pastva and David Šafránek.</span>
						<span class="papertitle" data-toggle="collapse" data-target="#98590080">High-Performance Symbolic Parameter Synthesis of Biological Models: A Case Study</span>
						<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590080"/>
					</li>

				</ul>
			</li>
		</ul>

		<h3>Thursday, 22nd September</h3>

		<ul class="list-group">
			<li class="list-group-item"><span id="invited3" class="fixHeaderOffset"></span>
				<h4 class="list-group-item-heading">09:00 - 10:00. Invited talk: <strong>Luca Cardelli</strong>. Chair: François Fages</h4>
				<span class="papertitle" data-toggle="collapse" data-target="#Invited_cardelli">Morphisms of reaction networks</span>
				<p class="collapse just list-group-item-text" style="font-size: 90%" id="Invited_cardelli"/>
			</li>
		</ul>

		<ul class="list-group">
			<li class="list-group-item"><span id="coffee3" class="fixHeaderOffset"></span>
				<p class="list-group-item-heading">10:00 - 10:30. Coffee break</p>
			</li>
		</ul>

		<ul class="list-group">
			<li class="list-group-item"><span id="session_2_1" class="fixHeaderOffset"></span>
				<h4 class="list-group-item-heading">10:30 - 11:30. Session 2.1: <strong>Case studies</strong>. Chair: Olivier Roux</h4>
				<ul style="font-size: 90%">
					<li class="list-group-item">
						<span class="authors">Qinsi Wang, Natasa Miskov-Zivanov, Bing Liu, James Faeder, Michael Lotze and Edmund Clarke.</span>
						<span class="papertitle" data-toggle="collapse" data-target="#98590281">Formal Modeling and Analysis of Pancreatic Cancer Microenvironment</span>
						<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590281"/>
					</li>
					<li class="list-group-item">
						<span class="authors"><a href="http://www3.cs.stonybrook.edu/~mdaislam">Md. Ariful Islam</a>, Greg Byrne, <a href="http://www.cs.cmu.edu/~soonhok">Soonho Kong</a>, <a href="http://www.cs.cmu.edu/~emc">Edmund Clarke</a>, <a href="https://www.cs.umd.edu/~rance">Rance Cleaveland</a>, <a href="https://ti.tuwien.ac.at/cps/people/grosu">Radu Grosu</a> and <a href="http://www3.cs.stonybrook.edu/~sas/">Scott Smolka</a>.</span>
						<span class="papertitle" data-toggle="collapse" data-target="#98590128">Bifurcation Analysis of Cardiac Alternans using  δ-Decidability</span>
						<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590128"/>
					</li>
				</ul>
			</li>
		</ul>

		<ul class="list-group">
			<li class="list-group-item"><span id="session_2_2" class="fixHeaderOffset"></span>
				<h4 class="list-group-item-heading">11:30 - 12:30. Session 2.2: <strong>Poster flashes</strong>. Chair: Nicola Paoletti</h4>
				<ul style="font-size: 80%">
					<li class="list-group-item">
						<span class="authors">Priya Anand, Monika Borkowska-Panek, Karin Fink and <a href="http://www.int.kit.edu/wenzel.php">Wolfgang Wenzel</a>.</span>
						<span class="papertitle" data-toggle="collapse" data-target="#98590318">Modelling Peptide Adsorption on Inorganic Surfaces</span>
						<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590318"/>
					</li>

					<li class="list-group-item">
						<span class="authors"><a href="http://loicpauleve.name">Loïc Paulevé</a>.</span>
						<span class="papertitle" data-toggle="collapse" data-target="#98590326">Pint, a static analyzer for dynamics of Automata Networks</span>
						<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590326"/>
					</li>

					<li class="list-group-item">
						<span class="authors">Nadia S. M. Goncalves, Samuel M. D. Oliveira, Jose M. Fonseca and Andre S. Ribeiro.</span>
						<span class="papertitle" data-toggle="collapse" data-target="#98590321">Temperature Dependence of Leakiness of Transcription Repression Mechanisms of Escherichia coli</span>
						<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590321"/>
					</li>

					<li class="list-group-item">
						<span class="authors"><a href="http://wwwen.uni.lu/recherche/fstc/computer_science_and_communications_research_unit/members/andrzej_mizera">Andrzej Mizera</a>, <a href="http://satoss.uni.lu/jun">Jun Pang</a> and Qixia Yuan.</span>
						<span class="papertitle" data-toggle="collapse" data-target="#98590323">GPU-accelerated Steady-State Analysis of Probabilistic Boolean Networks</span>
						<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590323"/>
					</li>
					<li class="list-group-item">
						<span class="authors"><a href="http://www.mrc-hnr.cam.ac.uk/people/james-smith/">James Smith</a>, Kai Loell and Albert Koulman.</span>
						<span class="papertitle" data-toggle="collapse" data-target="#98590333">Revealing biomarker mixtures in lipid pools from large-scale lipidomics</span>
						<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590333"/>
					</li>
					<li class="list-group-item">
						<span class="authors"><a href="http://www.mrc-hnr.cam.ac.uk/people/james-smith/">James Smith</a> and Ahmed Ibrahim.</span>
						<span class="papertitle" data-toggle="collapse" data-target="#98590332">Game theoretic consideration of transgenic bacteria in the human gut microbiota converting omega-6 to omega-3 fats</span>
						<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590332"/>
					</li>

					<li class="list-group-item">
						<span class="authors">Benjamin Hall, <a href="http://www.cs.le.ac.uk/people/npiterman">Nir Piterman</a> and <a href="http://research.microsoft.com/~jfisher/">Jasmin Fisher</a>.</span>
						<span class="papertitle" data-toggle="collapse" data-target="#98590328">Linear Temporal Logic for Biologists in BMA</span>
						<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590328"/>
					</li>
					<li class="list-group-item">
						<span class="authors">Mariana Esther Sanchez, Elena Alvarez-Buylla and Marcia Hiriart.</span>
						<span class="papertitle" data-toggle="collapse" data-target="#sanchez_et_al">The CD4+ T cell regulatory network mediates inflammatory responses during acute hyperinsulinemia</span>
						<p class="collapse just list-group-item-text" style="font-size: 90%" id="sanchez_et_al"/>
					</li>

					<li class="list-group-item">
						<span class="authors">David Shorthouse, Angela Riedel, Jacqueline Shields and Benjamin Hall.</span>
						<span class="papertitle" data-toggle="collapse" data-target="#98590330">Deregulation of Osmotic Regulation Machinery Explains and Predicts Cellular Transformation in Cancer and Disease</span>
						<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590330"/>
					</li>
				</ul>
			</li>
		</ul>

		<ul class="list-group">
			<li class="list-group-item"><span id="lunch2" class="fixHeaderOffset"></span>
				<h4 class="list-group-item-heading">12:30 - 14:00. Lunch + Poster session</h4>
			</li>
		</ul>

		<ul class="list-group">
			<li class="list-group-item"><span id="session_2_3" class="fixHeaderOffset"></span>
				<h4 class="list-group-item-heading">14:00 - 15:00. Session 2.3: <strong>Reaction Networks (1)</strong>. Chair: Jerome Feret</h4>
				<ul style="font-size: 90%">
					<li class="list-group-item">
						<span class="authors"><a href="http://lifeware.inria.fr/~fages">François Fages</a>, Thierry Martinez, David Rosenblueth and <a href="http://lifeware.inria.fr/~soliman/">Sylvain Soliman</a>.</span>
						<span class="papertitle" data-toggle="collapse" data-target="#98590095">Influence Systems vs Reaction Systems</span>
						<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590095"/>
					</li>
					<li class="list-group-item">
						<span class="authors">Elisa Tonello, <a href="http://www.cristal.univ-lille.fr/~madelain/">Guillaume Madelaine</a>, Etienne Farcot, <a href="http://www.cristal.univ-lille.fr/~lhoussai/">Cedric Lhoussaine</a> and <a href="http://researchers.lille.inria.fr/~niehren">Joachim Niehren</a>.</span>
						<span class="papertitle" data-toggle="collapse" data-target="#98590195">Normalizing Chemical Reaction Networks by Confluent Structural Simplification</span>
						<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590195"/>
					</li>
				</ul>
			</li>
		</ul>

		<ul class="list-group">
			<li class="list-group-item"><span id="coffee4" class="fixHeaderOffset"></span>
				<p class="list-group-item-heading">15:00 - 15:30. Coffee break</p>
			</li>
		</ul>

		<ul class="list-group">
			<li class="list-group-item"><span id="session_2_4" class="fixHeaderOffset"></span>
				<h4 class="list-group-item-heading">15:30 - 17:00. Session 2.4: <strong>Reaction Networks (2)</strong>. Chair: David Gilbert</h4>
				<ul style="font-size: 90%">
					<li class="list-group-item">
						<span class="authors">Luca Laurenti, <a href="http://LucaCardelli.name/">Luca Cardelli</a> and <a href="http://www.cs.ox.ac.uk/people/marta.kwiatkowska/">Marta Kwiatkowska</a>.</span>
						<span class="papertitle" data-toggle="collapse" data-target="#98590143">A Stochastic Hybrid Approximation for Chemical Kinetics Based on the Linear Noise Approximation</span>
						<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590143"/>
					</li>
					<li class="list-group-item">
						<span class="authors">Michael Backenköhler, <a href="http://bortolussi.dmg.units.it">Luca Bortolussi</a> and <a href="http://mosi.cs.uni-saarland.de">Verena Wolf</a>.</span>
						<span class="papertitle" data-toggle="collapse" data-target="#98590013">Generalized Method of Moments for Stochastic Reaction Networks in Equilibrium</span>
						<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590013"/>
					</li>
					<li class="list-group-item">
						<span class="authors">Chunyan Mu, Peter Dittrich, <a href="http://www.cs.bham.ac.uk/~parkerdx/">David Parker</a> and Jonathan E. Rowe.</span>
						<span class="papertitle" data-toggle="collapse" data-target="#98590226">Formal Quantitative Analysis of Reaction Networks Using Chemical Organisation Theory</span>
						<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590226"/>
					</li>
				</ul>
			</li>
		</ul>


		<ul class="list-group">
			<li class="list-group-item"><span id="award_cer" class="fixHeaderOffset"></span>
				<h4 class="list-group-item-heading">17:00 - 17:30. Award ceremony</h4>
			</li>
		</ul>

		<ul class="list-group">
			<li class="list-group-item"><span id="business_meeting" class="fixHeaderOffset"></span>
				<p class="list-group-item-heading">17:30 - 18:30. Business meeting</p>
			</li>
		</ul>

		<ul class="list-group">
			<li class="list-group-item"><span id="social_event" class="fixHeaderOffset"></span>
				<h4 class="list-group-item-heading">19:00 - 21:30. Social event + dinner.</h4>
				<p class="list-group-item-text"><a href="#dinner_emmanuel">Dinner at Emmanuel College</a></p>
			</li>
		</ul>

		<h3>Friday, 23rd September</h3>


		<ul class="list-group">
			<li class="list-group-item"><span id="invited4" class="fixHeaderOffset"></span>
				<h4 class="list-group-item-heading">09:00 - 10:00. Invited talk: <strong>Radu Grosu</strong>. Chair: Joelle Despeyroux</h4>
				<span class="papertitle" data-toggle="collapse" data-target="#Invited_grosu">From Artificial to Biological Neural Networks</span>
				<p class="collapse just list-group-item-text" style="font-size: 90%" id="Invited_grosu"/>
			</li>
		</ul>

		<ul class="list-group">
			<li class="list-group-item"><span id="coffee5" class="fixHeaderOffset"></span>
				<p class="list-group-item-heading">10:00 - 10:30. Coffee break</p>
			</li>
		</ul>

		<ul class="list-group">
			<li class="list-group-item"><span id="session_3_1" class="fixHeaderOffset"></span>
				<h4 class="list-group-item-heading">10:30 - 12:00. Session 3.1: <strong>Abstraction, reduction and approximation methods</strong>. Chair: David Šafránek</h4>
				<ul style="font-size: 90%">
					<li class="list-group-item">
						<span class="authors">Jasha Sommer-Simpson, John Reinitz, Leonid Fridlyand, Louis Philipson and Ovidiu Radulescu.</span>
						<span class="papertitle" data-toggle="collapse" data-target="#98590266">Hybrid reductions of computational models of voltage-gated ion channels coupled to cellular biochemistry</span>
						<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590266"/>
					</li>
					<li class="list-group-item">
						<span class="authors"><a href="http://loicpauleve.name">Loïc Paulevé</a>. </span>
						<span class="papertitle" data-toggle="collapse" data-target="#98590246">Goal-Oriented Reduction of Automata Networks</span>
						<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590246"/>
					</li>
					<li class="list-group-item">
						<span class="authors"><a href="http://www.di.ens.fr/~feret">Jerome Feret</a> and <a href="http://www.di.ens.fr/~quyen/">Quyen Kim Ly</a>.</span>
						<span class="papertitle" data-toggle="collapse" data-target="#98590113">Local traces: an over-approximation of the behaviour of the proteins in rule-based models</span>
						<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590113"/>
					</li>
				</ul>
			</li>
		</ul>

		<ul class="list-group">
			<li class="list-group-item"><span id="lunch3" class="fixHeaderOffset"></span>
				<p class="list-group-item-heading">12:00 - 13:30. Lunch</p>
			</li>
		</ul>

		<ul class="list-group">
			<li class="list-group-item"><span id="session_3_2" class="fixHeaderOffset"></span>
				<h4 class="list-group-item-heading">13:30 - 14:30. Session 3.2: <strong>Tools</strong>. Chair: Giulio Caravagna</h4>
				<ul style="font-size: 90%">
					<li class="list-group-item">
						<span class="authors"><a href="https://sites.google.com/site/alexfvillaverde/">Alejandro F. Villaverde</a>, Kolja Becker and <a href="http://gingproc.iim.csic.es/~julio/">Julio R. Banga</a>.</span>
						<span class="papertitle" data-toggle="collapse" data-target="#98590311">PREMER: parallel reverse engineering of biological networks with information theory</span>
						<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590311"/>
					</li>
					<li class="list-group-item">
						<span class="authors">Matej Troják, David Šafránek, Jakub Hrabec, Jakub Šalagovič, Františka Romanovská and Jan Červený.</span>
						<span class="papertitle" data-toggle="collapse" data-target="#98590305">E-cyanobacterium.org: A Web-based Platform for Systems Biology of Cyanobacteria</span>
						<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590305"/>
					</li>
					<li class="list-group-item">
						<span class="authors"><a href="http://wwwen.uni.lu/recherche/fstc/computer_science_and_communications_research_unit/members/andrzej_mizera">Andrzej Mizera</a>, <a href="http://satoss.uni.lu/jun">Jun Pang</a> and Qixia Yuan.</span>
						<span class="papertitle" data-toggle="collapse" data-target="#98590298">ASSA-PBN 2.0: A Software Tool for Probabilistic Boolean Networks</span>
						<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590298"/>
					</li>
				</ul>
			</li>
		</ul>
		
		<ul class="list-group">
			<li class="list-group-item"><span id="session_3_3" class="fixHeaderOffset"></span>
				<h4 class="list-group-item-heading">14:30 - 15:00. Session 3.3: <strong>Optimisation and control (2)</strong>. Chair: TBA </h4>
				<ul style="font-size: 90%">
					<li class="list-group-item">
						<span class="authors"><a href="http://combio.abo.fi/~eczeizle/">Eugen Czeizler</a>, Cristian Gratie, Krishna Kanhaiya and <a href="http://www.users.abo.fi/ipetre">Ion Petre</a>.</span>
						<span class="papertitle" data-toggle="collapse" data-target="#98590065">Target Controllability of Linear Networks</span>
						<p class="collapse just list-group-item-text" style="font-size: 90%" id="98590065"/>
					</li>
				</ul>
			</li>
		</ul>

		<ul class="list-group">
			<li class="list-group-item"><span id="closing" class="fixHeaderOffset"></span>
				<p class="list-group-item-heading">15:00 - 15:30. Closing</p>
			</li>
		</ul>

	</div>
</div>