<div class="panel panel-default">
	<div class="panel-body">
		<h1 style="text-align:center">Registration</h1>
		<div class="well" style="text-align:center">
			<a href="
			http://onlinesales.admin.cam.ac.uk/browse/extra_info.asp?compid=1&modid=2&deptid=102&catid=1277&prodid=1702" class="btn btn-info">Click here to register</a>
		</div>
		<h2>Fees</h2>
		<table class="table table-hover" style="width: auto;">
			<thead>
				<tr>
					<th></th>
					<th>Early<br>(before 15 August)</th>
					<th>Late &amp; on-site</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<th scope="row">Regular</th>
					<td>300 GBP</td>
					<td>400 GBP</td>
				</tr>
				<tr>
					<th scope="row">Student</th>
					<td>200 GBP</td>
					<td>300 GBP</td>
				</tr>
			</tbody>
		</table>
		

		
	</div>
</div>