<h1>Sponsors</h1>
<div class="panel panel-default">
	<div class="panel-body">
		<img src = "images/logo_nvidia.png" alt = "Nvidia logo" height="100"/>
		<h3><a href="http://www.nvidia.com/">NVIDIA</a></h3>
	</div>
</div>
<div class="panel panel-default">
	<div class="panel-body">
		<img src = "images/ieee_mb_blue_1.gif" alt = "IEEE logo" class=height="100"/>
		<h3><a href="https://www.computer.org/web/tcsim/index">IEEE Technical Committee on Simulation</a></h3>
	</div>
</div>