<div class="panel panel-default"><div class="panel-body">
	<h1 style="text-align:center">Venue</h1>
	<div class="row">
		<div class="col-md-6">
			<p>CMSB 2016 will be held in Cambridge, at the William Gates Building (aka the <a class="external-link" href="http://www.cl.cam.ac.uk/">Computer Laboratory</a>).</p>
			<h2>Accommodation</h2>
			<h4>Colleges</h4>
			Probably the best options for accomodation are provided by colleges. Almost all of the other colleges are within walking distance of the William Gates Building, and most offer accomodation. In particular, some of the closest are: 
			<ul>
				<li><a href="https://www.chu.cam.ac.uk/conferences/facilities/accommodation/">Churchill</a></li>
				<li><a href="https://www.robinson.cam.ac.uk/conferences/conference-accommodation">Robinson</a></li>
				<li><a href="http://www.sel.cam.ac.uk/conferences/accommodation/">Selwyn</a></li>
			</ul>
			Rooms in other colleges can also be found via <a href="http://www.universityrooms.com/en/city/cambridge/home">universityrooms.com</a>
			<h4>Hotels</h4>
			Hotels in Cambridge are mainly in the centre. Some of the biggest are the <a href="http://doubletree3.hilton.com/en/hotels/united-kingdom/doubletree-by-hilton-hotel-cambridge-city-centre-STNCBDI/index.html">Hilton</a>, the <a href="http://www.sjhotels.co.uk/cambridge">Royal Cambridge Hotel</a>, and <a href="https://www.hotelduvin.com/locations/cambridge/">Hotel du Vin</a>.
		</div>
		<div class="col-md-6">
		<img src="http://www.cl.cam.ac.uk/newlabphotos/WGB.Sept.2011/view_from_NW.jpg" width="100%">
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<iframe width="100%"" src="https://www.google.com/maps/d/embed?mid=1XKkPwQRewcqes5bGd_B8DZ-i6_0" width="640" height="480"></iframe>
		</div>
		<div class="col-md-6">
			<h2>Travel</h2>
			<h4>Around Cambridge</h4>
			Cambridge is small enough that walking and cycling are normally the best ways to get around. There's very little parking so driving isn't recommended, but the taxis are good.
			The "Uni 4" bus is also very useful - it goes past the William Gates Building, all the recommended colleges and hotels, and near to the railway station.
			<h4>Arriving by plane</h4>
			<p>Stansted Airport is the closest major airport, a ~40 minute train journey away from Cambridge by train.</p>
			<p>From other airports the best options is to go to London and take the train from King's Cross.</p>
			<h4>Arriving by train</h4>
			<a href="https://www.google.co.uk/maps/place/Cambridge/@52.1940817,0.1351237,17z/data=!3m1!4b1!4m5!3m4!1s0x47d87083c513efe3:0xc3b0831300f8d3f1!8m2!3d52.1940784!4d0.1373124">Cambridge Railway Station</a> is around an hour from London King's Cross or Liverpool Street, or 40 minutes from Stansted Airport. From the station it is best to take a taxi or the Uni 4 bus.
			<h4>Arriving by car</h4>
			<p>Madingley Road Park and Ride carpark is just over the road from the William Gates Building.</p>
		</div>
	</div>
</div></div>