<div class="panel panel-default">
  <div class="panel-body">
<h1 style="text-align:center">Venue</h1>
<p>CMSB 2016 will be held in Cambridge, at the William Gates Building (aka the <a class="external-link" href="http://www.cl.cam.ac.uk/">Computer Laboratory</a>).</p>
<h2>Accommodation</h2>
<!-- <p>To book accommodation at Churchill College, just a few minutes walk down the road from the William Gates Building, <a class="external-link" href="https://www.chu.cam.ac.uk/conferences/facilities/accommodation/" target="_self" title="">click here</a>.</p> -->
<!-- There are a number of colleges nearby which can offer accomodation:
<ul>
<li><a href="https://www.chu.cam.ac.uk/conferences/facilities/accommodation/">Churchill</a></li>
<li><a href="https://www.robinson.cam.ac.uk/conferences/conference-accommodation">Robinson</a></li>
<li><a href="http://www.sel.cam.ac.uk/conferences/accommodation/">Selwyn</a></li>
</ul> -->
Cambridge has a large number of hotels and colleges which can offer accommodation.
<h2>Travel</h2>
<p>The Computer Laboratory website has comprehensive directions by all modes of transport: </p>
<p><a href="http://www.cl.cam.ac.uk/directions/" target="_blank">www.cl.cam.ac.uk/directions/</a></p>
<p> </p>
<h3>By Train</h3>
<p>Cambridge Railway Station is around an hour from London King's Cross or Liverpool Street.</p>
<h3>By Plane</h3>
<p>Stansted Airport is the closest major airport, a ~40 minute train journey away from Cambridge.</p>
<h3>By Automobile</h3>
<p>Madingley Road Park and Ride carpark is just over the road from the William Gates Building.</p>
</div>
</div>