<div class="panel panel-default">
<div class="panel-body">
<h1 style="text-align:center">International Workshop on Automated Reasoning for Systems Biology and Medicine (ARSBM 2016)</h1>

The 1st International Workshop on Automated Reasoning for Systems Biology and Medicine (ARSBM)
will take place on 20 September 2016 at the University of Cambridge's Computing Laboratory, and
it will be co-located with <a href="https://www.cl.cam.ac.uk/events/cmsb2016/">CMSB 2016</a>.

ARSBM 2016 will focus on the theory of delta-satisfiability (Gao, Avigad, and Clarke, LICS 2012)
and its biological applications. Participation is free, but we kindly ask you to register - see below.

<h3>Program:</h3>
<ul>
<li>2:30-3.45pm: Nonlinear real arithmetic and delta-satisfiability (<a href="https://sites.google.com/site/zupaolo/">Paolo Zuliani</a>, Newcastle, UK)</li>
<li>3.45-4.30pm: Delta-complete decision procedures and hands-on tutorial (<a href="http://people.csail.mit.edu/zufferey/">Damien Zufferey</a>, MIT, USA)</li>
<li>4.30-4.45pm: Break</li>
<li>4.45-5:30pm: Stochastic hybrid systems: modelling cancer and psoriasis (<a href="http://homepages.cs.ncl.ac.uk/f.shmarov/">Fedor Shmarov</a>, Newcastle, UK)</li>
</ul>

<h3>Registration:</h3>

Please <a href="https://goo.gl/forms/nq83xTa7lDsRQDD93">register</a> so that we can order enough refreshments.

<h3>ARSBM 2016 Chairs:</h3>
<ul>
<li>Paolo Zuliani, Newcastle University</li>
<li>Pietro Lio', Cambridge University</li>
</ul>

</div>
</div>
