<div class="panel panel-default">
<div class="panel-body">
<h1>Workshop</h1>
A workshop on Automated Reasoning for Systems Biology will take place on 20th September 2016.

<h3>Tentative outline:</h3>
<ul>
<li>theory of delta-complete decision procedures (Sean Gao, MIT)</li>
<li>hands-on tutorial for dReal, dReach, dOp, and BioPSy (Soonho Kong, CMU and Fedor Shmarov, Newcastle)</li>
<li>applications to systems biology: cancer and psoriasis (Paolo Zuliani and Fedor Shmarov, Newcastle)</li>
<li>participants discuss open problems, challenges, collaboration opportunities, etc.</li>
</ul>

<p>More details coming soon.</p>
</div>
</div>